### ISSUE TITLE
Api with current queue size (Pending to be processed) 

### ISSUE THREAD

**Issue by saikatharryc** [judge0/judge0#210]
An API is required to provide with the current queue size, 

My Goal: To scale the application (workers), or spinup based on the requirement, I need to know how many of the jobs are at this point in time is pending to be processed. 
which I can compare with `/workers` result, which is the workers available and spinup more if needed accordingly.

**Comment by hermanzdosilovic** [comment]
I can add `size` to `/workers`.

**Comment by saikatharryc** [comment]
this will be a great addition.

in the near future a small addition will also be appreciated,
in this type of metrics endpoint, will it be possible to give the response in Prometheus format as well? while passing a specific query parameter?

**Comment by hermanzdosilovic** [comment]
Let's make one feature at the time. :) But Prometheus format makes sense.

**Comment by hermanzdosilovic** [comment]
This is released with v1.11.0.
