### ISSUE TITLE
Getting token after installation.

### ISSUE THREAD

**Issue by webrichardnet** [judge0/judge0#219]
Hello Guys
I hope you are fine

I've  followed all the deployment procedure steps but.., I need to know how to get the token or api-key.

I'd appreciate to know the steps to tests the environment or installation is working.

Please, step thoroughly.

Help me, thanks.

**Comment by hermanzdosilovic** [comment]
Hi @webrichardnet,

if you deployed Judge0 on your own server then you don't need any API key for using it.
