### ISSUE TITLE
The submissions API is not working

### ISSUE THREAD

**Issue by ajjaic** [judge0/judge0#221]
Hi. So I deployed judge0 in digital ocean.

The judge0 API is accessible.
I am able to make `GET` requests to `/system_info` and `/about` and `/statistics`.

But I am unable to make a `/submissions/?base64_encoded=false&wait=false` `POST` request with the following JSON payload. I even set the headers to `Content-Type: application/json`. But it is not working. Instead I get a `400` status with an empty body in the response. Could you please tell me if I am doing something wrong?

```json
{
  "source_code": "#include <stdio.h>\n\nint main(void) {\n  char name[10];\n  scanf(\"%s\", name);\n  printf(\"hello, %s\n\", name);\n  return 0;\n}",
  "language_id": 4,
  "stdin": "world"
}
```

Is there some initial configuration that I have to do to allow the server to accept code submissions?

**Comment by ajjaic** [comment]
I think I figured it out. For some reason adding the header "Content-Type: application/json" to my requests is creating a 400 Bad Request HTTP Status. When I remove the "Content-Type: application/json" header from the request, then it works.

I am using the python requests library.

**Comment by andilemashala** [comment]
im also experiencing the same problem with js fetch function
