### ISSUE TITLE
Deploying on local Machine (MAC)

### ISSUE THREAD

**Issue by Pulkit29** [judge0/judge0#222]
I am following the steps as mentioned in the Read Me doc.
https://github.com/judge0/api/blob/master/CHANGELOG.md#deployment-procedure

Deploying on my local Mac Machine.

Following v1.10.0 steps

Getting Permission denied error in following command

`docker-compose up db redis`

Following are the Error Logs I am getting : 

 
> The files belonging to this database system will be owned by user "postgres".
> db_1       | This user must also own the server process.
> db_1       | 
> db_1       | The database cluster will be initialized with locale "en_US.utf8".
> db_1       | The default database encoding has accordingly been set to "UTF8".
> db_1       | The default text search configuration will be set to "english".
> db_1       | 
> db_1       | Data page checksums are disabled.
> db_1       | 
> db_1       | initdb: directory "/var/lib/postgresql/data" exists but is not empty
> db_1       | If you want to create a new database system, either remove or empty
> db_1       | the directory "/var/lib/postgresql/data" or run initdb
> db_1       | with an argument other than "/var/lib/postgresql/data".
> db_1       | The files belonging to this database system will be owned by user "postgres".
> db_1       | This user must also own the server process.
> db_1       | 
> db_1       | The database cluster will be initialized with locale "en_US.utf8".
> db_1       | The default database encoding has accordingly been set to "UTF8".
> db_1       | The default text search configuration will be set to "english".
> db_1       | 
> db_1       | Data page checksums are disabled.
> db_1       | 
> db_1       | initdb: directory "/var/lib/postgresql/data" exists but is not empty
> db_1       | If you want to create a new database system, either remove or empty
> db_1       | the directory "/var/lib/postgresql/data" or run initdb
> db_1       | with an argument other than "/var/lib/postgresql/data".
> db_1       | The files belonging to this database system will be owned by user "postgres".
> db_1       | This user must also own the server process.
> db_1       | 
> db_1       | The database cluster will be initialized with locale "en_US.utf8".
> db_1       | The default database encoding has accordingly been set to "UTF8".
> db_1       | The default text search configuration will be set to "english".
> db_1       | 
> db_1       | Data page checksums are disabled.
> db_1       | 
> db_1       | initdb: directory "/var/lib/postgresql/data" exists but is not empty
> redis_1    | 1:C 30 Aug 12:05:17.355 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis_1    | 1:C 30 Aug 12:05:17.356 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
> redis_1    | 1:C 30 Aug 12:05:17.357 # Configuration loaded
> redis_1    | 1:M 30 Aug 12:05:17.361 # Can't open the append-only file: Permission denied
> redis_1    | 1:C 30 Aug 12:05:18.183 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis_1    | 1:C 30 Aug 12:05:18.187 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
> redis_1    | 1:C 30 Aug 12:05:18.187 # Configuration loaded
> redis_1    | 1:M 30 Aug 12:05:18.194 # Can't open the append-only file: Permission denied
> redis_1    | 1:C 30 Aug 12:05:19.067 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis_1    | 1:C 30 Aug 12:05:19.073 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
> redis_1    | 1:C 30 Aug 12:05:19.074 # Configuration loaded
> redis_1    | 1:M 30 Aug 12:05:19.081 # Can't open the append-only file: Permission denied
> redis_1    | 1:C 30 Aug 12:05:20.092 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis_1    | 1:C 30 Aug 12:05:20.092 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
> redis_1    | 1:C 30 Aug 12:05:20.093 # Configuration loaded
> redis_1    | 1:M 30 Aug 12:05:20.107 # Can't open the append-only file: Permission denied
> db_1       | If you want to create a new database system, either remove or empty
> db_1       | the directory "/var/lib/postgresql/data" or run initdb
> db_1       | with an argument other than "/var/lib/postgresql/data".
> db_1       | The files belonging to this database system will be owned by user "postgres".
> redis_1    | 1:C 30 Aug 12:05:21.446 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis_1    | 1:C 30 Aug 12:05:21.448 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
> db_1       | This user must also own the server process.
> db_1       | 
> db_1       | The database cluster will be initialized with locale "en_US.utf8".
> db_1       | The default database encoding has accordingly been set to "UTF8".
> db_1       | The default text search configuration will be set to "english".
> db_1       | 
> db_1       | Data page checksums are disabled.
> db_1       | 
> db_1       | initdb: directory "/var/lib/postgresql/data" exists but is not empty
> db_1       | If you want to create a new database system, either remove or empty
> db_1       | the directory "/var/lib/postgresql/data" or run initdb
> db_1       | with an argument other than "/var/lib/postgresql/data".
> redis_1    | 1:C 30 Aug 12:05:21.449 # Configuration loaded
> 

Can anyone help me to resolve this ?

**Comment by Pulkit29** [comment]
Just sharing the separate logs for command

`docker-compose up db`

Logs - 

> Pulling db (postgres:9.6)...
> 9.6: Pulling from library/postgres
> 75cb2ebf3b3c: Pull complete
> 3ca6415d2bca: Pull complete
> ac08e6372a7b: Pull complete
> b4394fce95ce: Pull complete
> 6edcd5da08e3: Pull complete
> 3380dcb7db08: Pull complete
> c7c147d9c90d: Pull complete
> 08ae47fef758: Pull complete
> 988b755ec587: Pull complete
> 5af3fce29ed1: Pull complete
> f3e3b2a2cff5: Pull complete
> 8f0827942dc8: Pull complete
> 67089c6aa0e6: Pull complete
> 58f20f5e0bec: Pull complete
> Digest: sha256:9aa0b86ae3be8de6f922441b913e8914e840c652b6880a642f42f98f5e2aaeaf
> Status: Downloaded newer image for postgres:9.6
> Creating judge0-v10_db_1 ... done
> Attaching to judge0-v10_db_1
> db_1       | The files belonging to this database system will be owned by user "postgres".
> db_1       | This user must also own the server process.
> db_1       | 
> db_1       | The database cluster will be initialized with locale "en_US.utf8".
> db_1       | The default database encoding has accordingly been set to "UTF8".
> db_1       | The default text search configuration will be set to "english".
> db_1       | 
> db_1       | Data page checksums are disabled.
> db_1       | 
> db_1       | initdb: could not access directory "/var/lib/postgresql/data": Permission denied


Someone Please help. I am trying to deploy on local machine

**Comment by Pulkit29** [comment]
Logs for command

`docker-compose up redis`

Logs -

```
Pulling redis (redis:4.0)...
4.0: Pulling from library/redis
54fec2fa59d0: Pull complete
9c94e11103d9: Pull complete
04ab1bfc453f: Pull complete
7988789e1fb7: Pull complete
8ce1bab2086c: Pull complete
40e134f79af1: Pull complete
Digest: sha256:2e03fdd159f4a08d2165ca1c92adde438ae4e3e6b0f74322ce013a78ee81c88d
Status: Downloaded newer image for redis:4.0
Creating judge0-v10_redis_1 ... done
Attaching to judge0-v10_redis_1
redis_1    | 1:C 01 Sep 13:43:38.161 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1    | 1:C 01 Sep 13:43:38.162 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1    | 1:C 01 Sep 13:43:38.162 # Configuration loaded
redis_1    | 1:M 01 Sep 13:43:38.163 # Can't open the append-only file: Permission denied
```

**Comment by hermanzdosilovic** [comment]
Dup #227
