### ISSUE TITLE
Submission results in high cpu usage -  kswapd0

### ISSUE THREAD

**Issue by noisytoken** [judge0/judge0#225]
On occasions when I submit a request, kswapd0 process starts taking too much of a cpu. And most of the time the submission ends up with a "time limit exceeded" error.

When this happens the whole sever becomes unresponsive.

How to address this?

**Comment by hermanzdosilovic** [comment]
Does this (
https://askubuntu.com/questions/259739/kswapd0-is-taking-a-lot-of-cpu#530661)
help?
