### ISSUE TITLE
[QUESTION] running multiple workers

### ISSUE THREAD

**Issue by MadhavJivrajani** [judge0/judge0#226]
Hi,

I'm trying to figure out how I can go about running multiple multiple workers for a single judge0 server. I'm assuming each "worker" would entail a worker container, a Redis container, and a Postgres container. Any tips on how I could go about doing so?

Thanks! :smile:

**Comment by vvalchev** [comment]
Hello Madhav,
I can only guess, but probably all runners should share the same PostgreSQL and Redis.
I think Redis is used like a messaging queue to notify worker that job is available. And the job itself might be in the DB.

Regards,
Valentin

**Comment by hermanzdosilovic** [comment]
Hi @MadhavJivrajani,

number of workers that you want to run in the single workers container can be adjusted with `COUNT` variable in the Judge0 configuration file.

If you want to run multiple worker containers where each has `COUNT` workers in it, then you need to scale that container. For example, this is how you can run 3 containers worker containers where each will have `COUNT` workers in it.

```
docker-compose up -d --scale workers=3
```

**Comment by MadhavJivrajani** [comment]
Oh, I see, thanks so much @hermanzdosilovic !
I had a follow-up question, assuming that we scale workers in the way you mentioned above, when requests are sent to the server, is load balancing taken care of? Or would that need to be set up explicitly?

**Comment by hermanzdosilovic** [comment]
It is taken care of by Rails server.

**Comment by MadhavJivrajani** [comment]
Thanks a ton! :smile:
