### ISSUE TITLE
Getting 500 on create submission api. Hosted on local Mac Machine

### ISSUE THREAD

**Issue by Pulkit29** [judge0/judge0#227]
Hello guys, Hope you are doing great.

I am trying to create a submission but getting  **500**  error code.
I have deployed code on Local Mac Machine. Can anyone please help me in fixing this ? 

```
curl -X POST \
  'http://192.168.99.100/submissions/?base64_encoded=false&wait=false' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 8ffeff69-ac79-68db-3f01-eb76ee19d795' \
  -H 'accept: application/json' \
  -d '{
  "source_code": "#include <stdio.h>\n\nint main(void) {\n  char name[10];\n  scanf(\"%s\", name);\n  printf(\"hello, %s\n\", name);\n  return 0;\n}",
  "language_id": 4,
  "stdin": "world"
}'
```

Response : 

> {
>     "status": 500,
>     "error": "Internal Server Error"
> }

**Comment by vvalchev** [comment]
Hello Pulkit29,
The command `docker logs <container>` if very useful in that case. Can you inspect the logs of the judge server and the worker - it may contain some clue about the problem.

Regards,
Valentin

**Comment by Pulkit29** [comment]
> Hello Pulkit29,
> The command `docker logs <container>` if very useful in that case. Can you inspect the logs of the judge server and the worker - it may contain some clue about the problem.
> 
> Regards,
> Valentin

Thanks for the sharing this command. Now in logs I can see the 

` Redis : NOAUTH Authorization required error`

Docker Config is as follows - 

```
redis:
    image: redis:4.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - "./srv/redis-data:/app:rw"
```

How can I solve this error ?

Any request is appreciated

**Comment by vvalchev** [comment]
IMHO you need to set `REDIS_PASSWORD` key in judge0.conf

**Comment by Pulkit29** [comment]
> IMHO you need to set `REDIS_PASSWORD` key in judge0.conf

It’s already mentioned in judge.conf file.


Do I need to install and configure Redis and Postgress separately on my system and use that password in judge0.conf file ?

**Comment by vvalchev** [comment]
I meant you should give a value to the password field. You should install redis/postgres by yourself - it's already in the docker-compose file.

Anyway, maybe you should try with the following commands:

```
docker-compose down -v
docker-compose up
```

The first command will remove all previous docker containers and (-v) volumes. This means all DB is also erased.
The second command will start it again in foreground so you can watch the logs.

**Comment by hermanzdosilovic** [comment]
Hi @Pulkit29,

since I don't have a macOS I was not able to test Judge0 there, and the same goes for Windows. That is why you might see similar questions in the issues.

If you are deploying Judge0 to production I would recommend using Linux, and if you are just trying things out I would recommend that you use Judge0 on RapidAPI. Feel free to send me an email if you have any additional questions about this.

Additionally, if you want to help me add support for macOS, i.e. test it and make it work "out of the box" please schedule a meeting with me so we can debug this issue and so I can see live what is happening.

@vvalchev thank you very much for your help. :heart: 

Best,
Herman

**Comment by vvalchev** [comment]
I'm on Mac too.

I've tested with the latest release - judge0-v1.11.0 - without any modifications to the configuration file.

So I did:

```
curl -X POST \
  'http://localhost/submissions/?base64_encoded=false&wait=false' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 8ffeff69-ac79-68db-3f01-eb76ee19d795' \
  -H 'accept: application/json' \
  -d '{
  "source_code": "#include <stdio.h>\n\nint main(void) {\n  char name[10];\n  scanf(\"%s\", name);\n  printf(\"hello, %s\n\", name);\n  return 0;\n}",
  "language_id": 75,
  "stdin": "world"
}'
```

See that I changed the language to 75, not 4, that seems to be deprecated. (For information - `{"id":75,"name":"C (Clang 7.0.1)"}`)

The POST call returned `{"token":"eb184885-e3fe-4b9e-b4c1-ecd24e80dc32"}`.

So I did `curl http://localhost/submissions/eb184885-e3fe-4b9e-b4c1-ecd24e80dc32` and got:
```
{"stdout":null,"time":null,"memory":null,"stderr":null,"token":"eb184885-e3fe-4b9e-b4c1-ecd24e80dc32","compile_output":"main.c:6:10: warning: missing terminating '\"' character [-Winvalid-pp-token]\n  printf(\"hello, %s\n         ^\nmain.c:6:10: error: expected expression\nmain.c:7:1: warning: missing terminating '\"' character [-Winvalid-pp-token]\n\", name);\n^\nmain.c:9:2: error: expected '}'\n}\n ^\nmain.c:3:16: note: to match this '{'\nint main(void) {\n               ^\n2 warnings and 2 errors generated.\n","message":null,"status":{"id":6,"description":"Compilation Error"}}%     
```

So it works on Mac. The problem is somewhere else.

**Comment by Pulkit29** [comment]
> I'm on Mac too.
> 
> I've tested with the latest release - judge0-v1.11.0 - without any modifications to the configuration file.
> 
> So I did:
> 
> ```
> curl -X POST \
>   'http://localhost/submissions/?base64_encoded=false&wait=false' \
>   -H 'Cache-Control: no-cache' \
>   -H 'Content-Type: application/json' \
>   -H 'Postman-Token: 8ffeff69-ac79-68db-3f01-eb76ee19d795' \
>   -H 'accept: application/json' \
>   -d '{
>   "source_code": "#include <stdio.h>\n\nint main(void) {\n  char name[10];\n  scanf(\"%s\", name);\n  printf(\"hello, %s\n\", name);\n  return 0;\n}",
>   "language_id": 75,
>   "stdin": "world"
> }'
> ```
> 
> See that I changed the language to 75, not 4, that seems to be deprecated. (For information - `{"id":75,"name":"C (Clang 7.0.1)"}`)
> 
> The POST call returned `{"token":"eb184885-e3fe-4b9e-b4c1-ecd24e80dc32"}`.
> 
> So I did `curl http://localhost/submissions/eb184885-e3fe-4b9e-b4c1-ecd24e80dc32` and got:
> 
> ```
> {"stdout":null,"time":null,"memory":null,"stderr":null,"token":"eb184885-e3fe-4b9e-b4c1-ecd24e80dc32","compile_output":"main.c:6:10: warning: missing terminating '\"' character [-Winvalid-pp-token]\n  printf(\"hello, %s\n         ^\nmain.c:6:10: error: expected expression\nmain.c:7:1: warning: missing terminating '\"' character [-Winvalid-pp-token]\n\", name);\n^\nmain.c:9:2: error: expected '}'\n}\n ^\nmain.c:3:16: note: to match this '{'\nint main(void) {\n               ^\n2 warnings and 2 errors generated.\n","message":null,"status":{"id":6,"description":"Compilation Error"}}%     
> ```
> 
> So it works on Mac. The problem is somewhere else.

Actually yes! You are right problem is not with API call. 

I an on macOS Cataline 10.15.2

If I just follow the steps for deployment as mentioned in the the repo, it doesn't work. 

```
wget https://github.com/judge0/judge0/releases/download/v1.11.0/judge0-v1.11.0.zip
unzip judge0-v1.11.0.zip

cd judge0-v1.11.0
docker-compose up db redis
```

At this step, I get error as follows -

> Creating network "judge0-v11002_default" with the default driver
> Creating judge0-v11002_redis_1 ... done
> Creating judge0-v11002_db_1    ... done
> Attaching to judge0-v11002_redis_1, judge0-v11002_db_1
> redis_1    | 1:C 10 Sep 11:35:13.882 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis_1    | 1:C 10 Sep 11:35:13.884 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
> redis_1    | 1:C 10 Sep 11:35:13.884 # Configuration loaded
> redis_1    | 1:M 10 Sep 11:35:13.886 # Can't open the append-only file: Permission denied
> db_1       | The files belonging to this database system will be owned by user "postgres".
> db_1       | This user must also own the server process.
> db_1       | 
> db_1       | The database cluster will be initialized with locale "en_US.utf8".
> db_1       | The default database encoding has accordingly been set to "UTF8".
> db_1       | The default text search configuration will be set to "english".
> db_1       | 
> db_1       | Data page checksums are disabled.
> db_1       | 
> db_1       | initdb: could not access directory "/var/lib/postgresql/data": Permission denied
> 

I solved this out by changing the volume in postgres db in docker-compose file -

```
db:
    image: postgres:9.6
    env_file: judge0.conf
    volumes:
      - "./srv/postgres-data:/app:rw"
      # - /var/lib/postgresql/data
      # - ./srv/postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always
``` 

After this it gives Redis : NOAUTH Authorization Required error 

To solve this, I update the docker-compose file as follows : 

```
redis:
    image: redis:4.0
    command: [
      "bash", "-c",
      # 'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
      'docker-entrypoint.sh --appendonly yes'
    ]
    env_file: judge0.conf
    volumes:
      - "./srv/redis-data:/app:rw"
```

After this It worked on my system. But I am not sure if above steps are the correct way to solve the issue.

I hope it will be clear as what is happening. If you can help with correct solution, it's really appreciated.
