### ISSUE TITLE
Java Program not executing

### ISSUE THREAD

**Issue by akashgp09** [judge0/judge0#228]
- I am able to successfully Run C/C++/Python Program but having issue in executing Java Program.
## This is the Code i am trying to Run  
> public class Main {
    public static void main(String[] args) {
        System.out.println("hello, world");
    }
} 
## Response i am getting back :

`{
compile_output: null
memory: null
message: null
status: {id: 2, description: "Processing"}
stderr: null
stdout: null
time: null
token: "c19ed54d-1f90-4695-b503-***********1"
}`

**Comment by akashgp09** [comment]
@hermanzdosilovic  @mejibyte

**Comment by hermanzdosilovic** [comment]
Hi @akashgp09,

do you experience this issue on RapidAPI or on your own instance of Judge0? Are you using the Standard or Extra edition?

**Comment by akashgp09** [comment]
> Hi @akashgp09,
> 
> do you experience this issue on RapidAPI or on your own instance of Judge0? Are you using the Standard or Extra edition?

Actually it was a mistake by my end. Now i have figured it out and it's working fine, Thank You 😊
