### ISSUE TITLE
workers is 0

### ISSUE THREAD

**Issue by sxiangs** [judge0/judge0#230]
http://139.159.239.104:4000/workers  test workers  it retrun []
this is docker status:
7aed33410edc        judge0/judge0:1.11.0                                         "./docker-entrypoi..."   21 minutes ago      Up 21 minutes                  0.0.0.0:4000->3000/tcp              judge0v1110_server_1
f52ab8f49a6a        judge0/judge0:1.11.0                                         "./docker-entrypoi..."   28 minutes ago      Up 7 seconds                   3000/tcp                            judge0v1110_workers_1
3071b8dd1f95        redis:4.0                                                    "docker-entrypoint..."   About an hour ago   Up About an hour               6379/tcp                            judge0v1110_redis_1
91870c54653f        postgres:9.6                                                 "docker-entrypoint..."   About an hour ago   Up About an hour               5432/tcp                            judge0v1110_db_1
it looks normal what is the problem thank you!

**Comment by abhishekv24** [comment]
@sxiangs how did you fix it?
I am also getting an empty array as response with my API version 1.5.0.

**Comment by bukyapavankumar** [comment]
same here

**Comment by hdsfx** [comment]
It will fix itself after running code.

**Comment by bukyapavankumar** [comment]
it didnt null responses in dummy client

**Comment by abhishekv24** [comment]
> It will fix itself after running code the first time.

It didn't for me. I am using API version 1.5.0.
