### ISSUE TITLE
install new python package 

### ISSUE THREAD

**Issue by MariamQusai** [judge0/judge0#232]
Hi, 
I need to install a  python package, I entered the docker container, but I do not know what files to modify, Can you please provide me even with high level instructions. 

thanks

**Comment by hermanzdosilovic** [comment]
Hi @MariamQusai,

Judge0 Extra is the perfect example for this use-case.

1. Create a Docker image similar to [this one](https://github.com/judge0/compilers/blob/master/extra/Dockerfile). Notice [this section](https://github.com/judge0/compilers/blob/master/extra/Dockerfile#L4-L12) where I have installed all packages that I need.
2. Build that image.
3. Edit [this](https://github.com/judge0/judge0/blob/extra/Dockerfile) Docker image and inherit (`FROM`) from the image you have built.
4. Add you language [here](https://github.com/judge0/judge0/blob/extra/db/languages/active.rb).
5. Build that image.

**Comment by Datum-Guy** [comment]
@hermanzdosilovic I am trying to deploy the judge0 on my instance following the instructions you mentioned above as I want to have custom packages installed into the build. 

However, I am not clear on the step 4. Maybe I am making a very silly mistake with my understanding of docker. I would really appreciate if you can clarify even a little bit on step 4. Specifically, where can I find the active.rb file once I have made the changes till step 3.

**Comment by amsanket22** [comment]
is this such docker image already exist with all these ML packages? cause I am using 1.13 and pandas is still not there

**Comment by QuantBuddyIO** [comment]
Say I want to make an optimized compiler for only PythonML - but I also want to include the panadaql library. 
What would I need to remove to make a more optimized image (don't pull unnecessary dependencies)
