### ISSUE TITLE
Cors Error

### ISSUE THREAD

**Issue by akashgp09** [judge0/judge0#236]
<img src="https://i.imgur.com/a2VGpO9.png">
Ever Since i am using judge0, I have Never faced this issue.<br />
Even Judge0 Demo Compiler https://online-compiler.dosilovic.com/ is not functioning

**Comment by bukyapavankumar** [comment]
is this fixed? @akashgp09

**Comment by akashgp09** [comment]
> is this fixed? @akashgp09

Yes it's Fixed now. And Everything Works A++ Now.
Thanks to @hermanzdosilovic

**Comment by bukyapavankumar** [comment]
how did you fix thatim getting cors errors too?

**Comment by akashgp09** [comment]
@bukyapavankumar Which method are you using to make request to the Judge0 API ?

**Comment by bukyapavankumar** [comment]
http method

**Comment by akashgp09** [comment]
Can you post the error message that you are getting.

**Comment by bukyapavankumar** [comment]
![Uploading Screenshot from 2020-10-12 12-07-44.png…]()

**Comment by bukyapavankumar** [comment]
WHEN I CHANGE MY PROJECT TO PORT 3000. I GET THESE
![Screenshot from 2020-10-12 12-22-59](https://user-images.githubusercontent.com/25202276/95714368-bf06a700-0c85-11eb-9d86-05d119a9be8b.png)

**Comment by bukyapavankumar** [comment]
IF I HOST MY APP ON ONE PORT AND SERVER ON OTHER PORT II GET THIS ERROR OTHERS WISE ITS WORKING.BUT WHEN I RUN CODE IT ONLY SHOWS COMPILE OUTPUT WITH ERRR EVEN THOUGH CODE IS PERFECT.

**Comment by akashgp09** [comment]
**For your first Question :**
You need to enable cors so that you can make request to the server from your frontend.
**For your second Question :**
Can't Exactly say what's wrong without looking the code.

**Comment by bukyapavankumar** [comment]
Fixed,thanks anyways
