### ISSUE TITLE
Assembly (NASM 2.14.02) example

### ISSUE THREAD

**Issue by edge555** [judge0/judge0#239]
I am sorry for this silly question but can I have an example code of this language to compile with the api?

**Comment by hermanzdosilovic** [comment]
Hi @edge555,

even though I responded to your email I will answer also here. :)

I am attaching the example code.

[main.txt](https://github.com/judge0/judge0/files/5506373/main.txt)
```
section	.text
    global _start

_start:

    xor	eax, eax
    lea	edx, [rax+len]
    mov	al, 1
    mov	esi, msg
    mov	edi, eax
    syscall

    xor	edi, edi
    lea	eax, [rdi+60]
    syscall

section	.rodata

msg	db 'hello, world', 0xa
len	equ	$ - msg
```

the same code can be found as the default code for that language in Judge0 IDE (https://ide.judge0.com).

**Comment by edge555** [comment]
Thank you so much :)

**Comment by edge555** [comment]
Thanks a lot!
