### ISSUE TITLE
Java POST 400 error

### ISSUE THREAD

**Issue by devfoFikiCar** [judge0/judge0#241]
Getting 400 error when using API in java.
Using okhttp3 4.9.0

Code:
`

            OkHttpClient client = new OkHttpClient();
            
             MediaType mediaType = MediaType.parse("application/json");
            
            RequestBody requestBody = RequestBody.create("{\n" +
                    "\"language_id\":" + languageID + ",\n" +
                    "\"source_code\":\"" + parseCode(code) + "\",\n" +
                    "}", mediaType);

            Request request = new Request.Builder()
                    .url("https://judge0.p.rapidapi.com/submissions")
                    .post(requestBody)
                    .addHeader("content-type", "application/json")
                    .addHeader("x-rapidapi-key", "KEY")
                    .addHeader("x-rapidapi-host", "judge0.p.rapidapi.com")
                    .addHeader("wait", "true")
                    .build();

            Response response = client.newCall(request).execute();

            String rd = response.body().string();

            System.out.println("rd" + " " + rd);
`

rd is always null and in the dashboard, on rapid API I get 400 error.

Code where I call this code:
`

public class test extends android.os.AsyncTask<String, Integer, String> {

        @Override
        protected void onPreExecute() {
            alertDialog = new SpotsDialog.Builder()
                    .setContext(getContext())
                    .setMessage("Executing code")
                    .setCancelable(false)
                    .build();
            alertDialog.show();
            btRun.setEnabled(false);
        }

        @Override
        protected void onPostExecute(String s) {
            alertDialog.dismiss();
            btRun.setEnabled(true);
        }

        @Override
        protected String doInBackground(String... strings) {
            String token = SubmitCode.requestToken(strings[0], LANGUAGE);
            String out = RetrieveOutput.getOutput(token);
            return out;
        }
    }
`

**Comment by vvalchev** [comment]
Try with:
```
 .addHeader("acccept", "application/json")

```

**Comment by devfoFikiCar** [comment]
> Try with:
> 
> ```
>  .addHeader("acccept", "application/json")
> ```

That works fine, for future references my code doesn't work when run on android but works in other cases.
