### ISSUE TITLE
Is it possible to enable networking?

### ISSUE THREAD

**Issue by oliver-hoff** [judge0/judge0#243]
Curious if it would be possible to allow networking and make http requests from Judge0. I tried calling the following ruby code on https://ide.judge0.com/:

```
require 'net/http'

url = URI.parse('http://www.example.com/index.html')
req = Net::HTTP::Get.new(url.to_s)
res = Net::HTTP.start(url.host, url.port) {|http|
  http.request(req)
}
puts res.body
```

I get the following error: 

```
/usr/local/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to www.example.com:80 (getaddrinfo: Temporary failure in name resolution) (SocketError)
	from /usr/local/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:960:in `open'
	from /usr/local/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
	from /usr/local/ruby-2.7.0/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
	from /usr/local/ruby-2.7.0/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
	from /usr/local/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:958:in `connect'
	from /usr/local/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
	from /usr/local/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:932:in `start'
	from /usr/local/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:606:in `start'
	from script.rb:5:in `<main>'
```

Upon reading here: https://github.com/ioi/isolate/issues/74

It seems isolate allows for the possibility of allowing networking. Are there any plans to enable this as an option?

Thanks!

**Comment by hermanzdosilovic** [comment]
Hi @oliver-hoff,

yes, we plan to add support for networking in the near future. :)

**Comment by oliver-hoff** [comment]
@hermanzdosilovic thanks. This is actually something really important for my use case. I am happy to work on this and create PR to make it happen. Any guidance you could provide into how to go about this? I can try the isolate approach mentioned in the PR I linked to, and take it from there.

**Comment by hermanzdosilovic** [comment]
@oliver-hoff, I would love to hear more about your use-case for this feature. Please send me an email.

**Comment by hermanzdosilovic** [comment]
This works with [Judge0 v1.13.0](https://github.com/judge0/judge0/releases/tag/v1.13.0) I am linking it with [the commit](https://github.com/judge0/judge0/commit/62a00520692c2b7a8bf0f54528aee8fbbf864f36) where the change was made.
