### ISSUE TITLE
[IMPORTANT] New Pricing, Features and More.

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/judge0#244]
> **tl;dr** Since **January 5th, 2021** Judge0 will **only** be available under new APIs on RapidAPI which include new features and pricing plans - [Judge0 CE](https://judge0.com/ce) and [Judge0 Extra CE](https://judge0.com/extra-ce).

# Introduction
It's been a while since our [last big announcement](https://github.com/judge0/judge0/issues/171) when we went Freemium with Judge0 in June this year. Our goal was to move Judge0 product development even further and give you the best possible online code execution service out there.

Now with more than **800 users** on RapidAPI, **160** active self-hosted instances of Judge0 around the world, and more than [**9.8 million**](https://judge0.com/statistics) code executions on our infrastructure, we are ready for the next big step in Judge0 development as a product and as a business.

In this annoucement we will talk about:
- [Judge0 Flavors and Editions](#flavors-and-editions)
- [New Pricing and Features](#new-pricing-and-features)
- [Judge0 Widgets](#judge0-widgets)

## Flavors and Editions
As you may already know, Judge0 comes in two flavors: **Judge0** and **Judge0 Extra**. They differ in the supported languages which can be found [here](https://github.com/judge0/judge0#supported-languages).

As of today, we are introducing two editions of Judge0: **Community Edition** and **Enterprise Edition**.

Community Edition of Judge0, i.e. **Judge0 CE** is the edition of Judge0 with publicly available source code licensed under [GPL-3.0](https://github.com/judge0/judge0/blob/master/LICENSE). This edition comes in two flavors: **Judge0 CE** and **Judge0 Extra CE**.

**Enterprise Edition** of Judge0, i.e. **Judge0 EE** is coming in Q2 2021. **Judge0 EE** and **Judge0 Extra EE** will be closed-sourced and will have additional features that won't be available in Community Edition.

Thus, as of today we have:
- **Judge0 CE** - previously know as **Judge0**.
- **Judge0 Extra CE** - previously known as **Judge0 Extra**.
- **Judge0 EE** - coming in Q2 2021
- **Judge0 Extra EE** - coming in Q2 2021

# New Pricing and Features
In June 2020 we moved to Freemium on RapidAPI with [Judge0](https://rapidapi.com/hermanzdosilovic/api/judge0) and [Judge0 Extra](https://rapidapi.com/hermanzdosilovic/api/judge0-extra). These APIs will be **shutdown** on January 5th, 2021 in favor of [**Judge0 CE**](https://judge0.com/ce) and [**Judge0 Extra CE**](https://judge0.com/extra-ce).

You will still be able to use our old APIs on RapidAPI till the above date.

Our new pricings are available on both RapidAPI and on our [**website**](https://judge0.com/#pricing).

With the new APIs on RapidAPI we are giving you new features:
1. Synchronous code execution (`wait=true`),
2. Judge0 Widgets, and
3. Pastes

### How to migrate from old to new?
Migration is really easy:

1. Choose a plan on the new API.
2. Unsubscribe from the old API.
2. In your app change `X-RapidApi-Host` header to point to the new API. [**View example**](https://github.com/hermanzdosilovic/online-compiler/commit/43002b006db33837ad7a13e751bd6f1204f6f1c9).

# Judge0 Widgets
Our latest product [**Judge0 Widgets**](https://widgets.judge0.com) allows you to easily integrate online code editor with code execution (a.k.a. online compiler) to your website with our embeddable web widgets.

It is fully integrated with RapidAPI in the terms of creating a widget and executing code.

# Questions?

Have a question about these changes? Feel free to ask them below or send us an email at contact@judge0.com.

**Comment by bummoblizard** [comment]
Great! Truly appreciate your work and happy to see the project growing. What additional features are you planning to add in Judge0 EE? And what ‘Pastes’ is exactly?

**Comment by hermanzdosilovic** [comment]
Hi @bummoblizard,
thank you for your nice words. I really appreciate it. :)

Pastes allow you to save arbitrary source code with us. It can be used for saving user's code snippets. In the next few weeks, we will integrate pastes with Judge0 IDE and you will be able to use our IDE with your RapidAPI key on your own website under your own domain. The integration will be even easier than it currently is.

As for Judge0 EE, our plan is to add some of the currently existing feature requests (available under GitHub issues) to the EE.

**Comment by YashKumarVerma** [comment]
I believe that this was very much needed, as this exemplary piece of technology needs to be taken forward.

**Comment by jacobjzhang** [comment]
One quick note, to reduce downtime, swap steps 2 & 3  like I did.

Thanks @hermanzdosilovic, the change was quick and seamless. I procrastinated for a week and got it done in 10 minutes 😆
