### ISSUE TITLE
Infinite IN_QUEUE status 

### ISSUE THREAD

**Issue by YashKumarVerma** [judge0/judge0#246]
I have judge0 (latest version) deployed on an azure VM (running on port 3000, mapped from docker-compose).

I recently encountered two submissions that had status as 1 (in-queue) permanent. I'm not sure if the stats for workers are helpful in this, but posting all data that I can share about the problem.

Code Submitted : (send into request as base64, note that this produces no output)
```js
function display(){
    fileToBase64( 'temp.txt' , './temp.txt' ).then(result => {
      console.log(result);
      document.getElementById("res").innerHTML += result;
    });
  }

// Convert file to base64 string
function fileToBase64 (filename, filepath){
    return new Promise(resolve => {
      var file = new File([filename], filepath);
      var reader = new FileReader();
      // Read file content on file loaded event
      reader.onload = function(event) {
        resolve(event.target.result);
      };
      
      // Convert data to base64 
      reader.readAsText(file);
    });
  };
  // Example call:
```

On submission, I get a judge0 token, and on accessing `http://xxx.xxx.xxx.xxx:xxx/token`, I always get the status as 0.

Workers
```
[
  {
    "queue": "1.6.0",
    "available": 1,
    "idle": 1,
    "working": 0,
    "paused": 0,
    "failed": 0
  }
]
```

**Comment by hermanzdosilovic** [comment]
Hi @YashKumarVerma,

I assume you resolved this problem yourself?

What was the issue?

**Comment by RitikChauhan5132** [comment]
I am still getting this issue
Explaination : I have setup own judge api environment on docker and it's working fine
Api's like https://judge0.qkkalabs.com/languages are woking fine for me and giving desired output
While creating submission by hitting this api
https://judge0.qkkalabs.com/submissions?base64_encoded=true&fields=*
I am getting token but while getting output of code by hitting api

Query : https://judge0-ce.p.rapidapi.com/submissions/1b4b9444-bead-4fd2-901c-f0f307cacf2e?base64_encoded=true&fields=*
I am always getting this output
{
"source_code": "Y29uc29sZS5sb2coIjExMiIp\n",
"language_id": 63,
"stdin": "SnVkZ2Uw\n",
"expected_output": null,
"stdout": null,
"status_id": 1,
"created_at": "2024-04-03T06:50:24.655Z",
"finished_at": null,
"time": null,
"memory": null,
"stderr": null,
"token": "248dd9ad-d9f7-4cce-a14e-ff9d42306d35",
"number_of_runs": 1,
"cpu_time_limit": "5.0",
"cpu_extra_time": "1.0",
"wall_time_limit": "10.0",
"memory_limit": 128000,
"stack_limit": 64000,
"max_processes_and_or_threads": 60,
"enable_per_process_and_thread_time_limit": false,
"enable_per_process_and_thread_memory_limit": false,
"max_file_size": 1024,
"compile_output": null,
"exit_code": null,
"exit_signal": null,
"message": null,
"wall_time": null,
"compiler_options": null,
"command_line_arguments": null,
"redirect_stderr_to_stdout": false,
"callback_url": null,
"additional_files": null,
"enable_network": false,
"status": {
"id": 1,
"description": "In Queue"
},
"language": {
"id": 63,
"name": "JavaScript (Node.js 12.14.0)"
}
}

I used to call it in settimeout and setTimeInterval also but the response is same
Please provide me answer regarding this issue
