### ISSUE TITLE
Cannot access Judge0 through HTTPS and custom domain

### ISSUE THREAD

**Issue by vishnupsatish** [judge0/judge0#249]
I have installed Judge0 in an AWS EC2 instance using the instructions provided. I changed the VIRTUAL_HOST AND LETSENCRYPT_HOST variables to match the domain where I want to serve Judge0. I then changed LETSENCRYPT_EMAIL to my email address. Then, I went to my domain.com control panel and added an "A" record with the name being my subdomain and the content being the elastic IP address associated with the AWS EC2 instance. I tried to access the site at the domain specified in the variable "VIRTUAL_HOST", but the connection would time out. How can I fix this issue?

Edit: I had to add a security group to allow HTTPS access which I did, but now it's saying 500 Internal Server Error

**Comment by hermanzdosilovic** [comment]
Hey @vishnupsatish, please [schedule a meeting with me](https://judge0.appointlet.com) so we can take a look at the problem together.

**Comment by vishnupsatish** [comment]
This problem was fixed by deleting and re-installing Judge0. The website was not accessible since you must create a security group in EC2 allowing HTTP and HTTPS inbound traffic to your instance's public IP and domains(s).
