### ISSUE TITLE
Callback URL Doesn't Work

### ISSUE THREAD

**Issue by iamdejan** [judge0/judge0#255]
I have an issue when I try to receive a submission's result using callback URL.

Request:
```sh
curl --location --request POST 'http://localhost:4000/submissions/?wait=false' \
--header 'Content-Type: application/json' \
--header 'Cookie: fusionauth.locale=en_US' \
--data-raw '{
    "source_code": "#include <cstdio>\r\n\r\nint main() {\r\n    char world[20];\r\n    scanf(\"%s\", world);\r\n    printf(\"Hello, %s\", world);\r\n}\r\n",
    "language_id": 76,
    "stdin": "world",
    "expected_output": "hello, Judge0",
    "callback_url": "http://localhost:5000/callback"
}'
```

My server code (written in Python 3.8 and Flask):
```python3
import sys

from flask import Flask, request, make_response

app = Flask(__name__)


@app.route('/')
def hello_world():
    return 'Hello World!'


@app.route('/callback', methods=['PUT'])
def receive_result():
    response = request.data.decode("ascii")
    print(response, file=sys.stderr)

    r = make_response(response)
    r.mimetype = 'application/json'
    return r


if __name__ == '__main__':
    app.run()

```

The issue is that the callback URL is never called, even after the submission is finished (I try to get submission manually).

Did I do anything wrong? Thanks in advance.

**Comment by vvalchev** [comment]
When you provide `http://localhost:5000/callback` for Judge0, that would be the Judge0 system itself.

If you are running Judge0 using docker, maybe you callback url should be `http://host.docker.internal:5000/callback`

**Comment by iamdejan** [comment]
@vvalchev thank you, this works.

**Comment by vishal-lokare** [comment]
> When you provide `http://localhost:5000/callback` for Judge0, that would be the Judge0 system itself.
> 
> If you are running Judge0 using docker, maybe you callback url should be `http://host.docker.internal:5000/callback`

Hi, I have tried this and many other solutions but still it is not working. If possible, can you share your 'judge0 server' container's logs? I want to see what does it log while sending the data to "callback_url". In my deployment, I can't see any log related to this, nor am I receiving any data in my "callback_url".
