### ISSUE TITLE
Number of workers increase each time restart server 

### ISSUE THREAD

**Issue by ncthuc** [judge0/judge0#256]
The number of workers (/workers) sometimes not correct after add/remove worker nodes. And when I try to restart the server by `docker-compose restart` / or even `docker-compose down`, then `docker-compose up`, the number of workers event increases faster. 

The workaround I am using is `docker-compose down`, then delete the redis volume, then `docker-compose up` again, which is very troublesome. Can someone please take a look.

**Comment by ncthuc** [comment]
I figured out a faster way to work around this, using `docker-compose rm redis` to remove only redis service, then delete the redis volume, then `docker-compose up -d redis` to start it again.

Anyway how can we do this in proper way?

**Comment by hermanzdosilovic** [comment]
Hi @ncthuc,

this was a bug, has been fixed and will be released in the next release.

Thank you for your contribution!
