### ISSUE TITLE
Deploying on AWS

### ISSUE THREAD

**Issue by thecodersatish** [judge0/judge0#260]
Bro ,can anyone please tell me step by step process of how to install this in AWS services

**Comment by phamngocquy** [comment]
In my opinion, is setup docker judge0 on EC2 instance of AWS

**Comment by hermanzdosilovic** [comment]
Hi @thecodersatish,

I am not familiar with the setup of Judge0 on AWS, maybe somebody else can help here.

**Comment by cameronweibel** [comment]
I have judge0 running on AWS Elastic Beanstalk. Here are the steps:
1. Download the zip from [here ](https://github.com/judge0/judge0/blob/extra/CHANGELOG.md)(HTTP). As of the time of writing, the URL is: https://github.com/judge0/judge0/releases/download/v1.13.0-extra/judge0-v1.13.0-extra.zip.
2. Unzip the folder so you have _judge0-v1.13.0-extra_ and within it the _judge0.conf_ and _docker-compose.yml_ files. You'll need to zip just these two files so you _judge0.zip_ with these two files in the root of the folder.
3. Go to AWS Elastic Beanstalk and create a new environment with the following settings: 
- Type: Web server environment
- Application name: judge0 (or whatever you want)
- Environment info: You can leave this blank
- Platform: Managed, Docker, Docker running on 64bit Amazon Linux 2, 3.2.6 (latest version as of writing)
- Application code: Upload your zip folder _judge0.zip_ here.
- Select _Configure more options_ and  go to _Instances_ and add 20 GB of magnetic storage in the root volume, then go to  _Capacity_ and change the instance type to t2.small (you'll want at least 1.5 GB of RAM and t2.small has 2 GB).

Click _Create environment_ to create the instance. 

Now you need to allow traffic on port 2358, where judge0 is expecting traffic. If you go to the EC2 dashboard, you can click the checkbox next to your new instance, click the _Security_ tab, click the link in _Security groups_ and add an inbound rule to allow Custom TCP, port 2358, 0.0.0.0/0 CIDR group. Go back to the EC2 dashboard, click your instance, go to _Instance summary_ and navigate to http://EC2_PUBLIC_IP:2358/about in the browser. You should see something like the following, which indicates that it's working:

`{"version":"1.13.0-extra","homepage":"https://judge0.com","source_code":"https://github.com/judge0/judge0","maintainer":"Herman Zvonimir Došilović \u003chermanz.dosilovic@gmail.com\u003e"}`

**Comment by hermanzdosilovic** [comment]
Thank you very much @cameronweibel.

**Comment by cameronweibel** [comment]
Which image did you use? Also, did you configure the security rules for ports 80 and 2358?

**Comment by TheArrowsmith** [comment]
Hi @cameronweibel , thanks for the detailed guide. Unfortunately I can't get things to work. I've got as far as clicking "Create environment" but after that I can't see anything about security groups.  In "Elastic Beanstalk > Environments > Judge0-env" I see these errors under Recent Events:

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/85154056/142907428-142eeaf3-396d-45a2-889d-fd2a1f1ba277.png">

I see a set of options related to 'security' but nothing about security groups:

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/85154056/142907595-71925107-2dc4-4a22-a832-6bf77e082eed.png">

And on the 'health' page I can see that my app's status is "No data", whatever that means:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/85154056/142907684-4f7e24c3-49e5-4078-b385-e6d7bdb6d115.png">

I'm new to all of this and I have no idea what's going on or what I should try. Do you have any pointers?

Thanks for your help!

**Comment by TheArrowsmith** [comment]
Update: I gave up on AWS and was able to get it working on Google Cloud Platform following [this tutorial](https://medium.com/javarevisited/lets-deploy-our-online-code-executor-in-google-cloud-e76a9fabac57).

One thing missing from that tutorial is that I needed to [add a firewall rule](https://cloud.google.com/vpc/docs/using-firewalls) allowing TCP ingress on port 2358. Until I did that, requests to my IP didn't work (I got 'Connection timed out'.)

**Comment by saifkhan7865** [comment]
Hey @cameronweibel I have done what you have said, I can access the docker website from the instance level i.e. IP address:2358

but when I access it from the URL provided by the elastic beanstalk it shows 502 bad gateway ( there is something that I'm missing here because I cannot access from the URL but I can only access it from the IPv4 address of the EC2 instance ) 

![image](https://user-images.githubusercontent.com/60229505/149379050-d062be68-20f1-417e-9543-cf19504729e0.png)


this is the configuration of my load balancers.
![image](https://user-images.githubusercontent.com/60229505/149379620-d6c71140-15a5-41ae-b1a0-08ee7a268dc2.png)

and this is my security group
![image](https://user-images.githubusercontent.com/60229505/149379687-37bbf67f-79fe-4fdc-b11c-29c5d0ccdcc1.png)

Please let me know what is that thing that I'm missing here.

**Comment by cameronweibel** [comment]
@saifkhan7865 If you're accessing the instance with the EB URL (over HTTP I assume), you need to forward the traffic to port 2358. Try accessing the IP addr directly IP_ADDRESS:80. Do you get the same 502 error?

**Comment by saifkhan7865** [comment]
> @saifkhan7865 If you're accessing the instance with the EB URL (over HTTP I assume), you need to forward the traffic to port 2358. Try accessing the IP addr directly IP_ADDRESS:80. Do you get the same 502 error?

Yeah it is HTTP, but How do I get the IP URL of EB? And how do I forward the traffic to port 2358 (i mean what setting do i change)
(note: when I'm accessing It with IP address of the instance deployed like "instance ip":2358 it works)

**Comment by cameronweibel** [comment]
@saifkhan7865 In general you can get the IP addr from the headers:

![image](https://user-images.githubusercontent.com/8155129/149493130-c532cd54-84e4-4083-929d-7c9b4132373a.png)

Here are my ALB settings:

![image](https://user-images.githubusercontent.com/8155129/149493533-0a2c7e11-2f9c-4b78-be7c-c1a21d3e895b.png)

**Comment by saifkhan7865** [comment]
@cameronweibel Hey I figured out what was the actual issue with it, I just had to add the process to the port 80 listener and it started working, thank you for helping me out. 

![image](https://user-images.githubusercontent.com/60229505/149493873-ce6e9c6c-60f2-461a-9d8f-f0549a024dcd.png)

**Comment by tartanapp** [comment]
hi,
can anyone help on how to deploy judge0 in azure container/docker ?

**Comment by Abhilalks** [comment]
How could I set the access control policy to the APIs.?

**Comment by Anuj-Kumar-Sharma** [comment]
@cameronweibel I have followed all the steps mentioned by you. But my elasticbeanstalk application is failing. It's giving this error inside the eb-engine.log

> {"status":"FAILURE","api_version":"1.0","results":[{"status":"FAILURE","msg":"Engine execution has encountered an error.","returncode":1,"events":[{"msg":"Instance deployment: Both 'Dockerfile' and 'Dockerrun.aws.json' are missing in your source bundle. Include at least one of them. The deployment failed.","timestamp":1678799861726,"severity":"ERROR"},{"msg":"Instance deployment failed. For details, see 'eb-engine.log'.","timestamp":1678799861726,"severity":"ERROR"}]}]}

**Comment by waitingonalice** [comment]
For those who have successfully deployed to aws elastic beanstalk, did you enable public IP for your ec2 instance. Wouldnt make sense to right? Since there exists a public load balancer to route traffic to that instance. 

The domain from aws elastic beanstalk keeps throwing 502 bad gateway after following all the instructions above. Even managed to deploy the containerized app successfully.

**Comment by SAM-BOGHARA** [comment]
I successfully self hosted judge0 on Amazon EC2 and api is working well(checked with postman). 

My React application(localhost)  is sending code and receiving proper output ,everything working fine.

However,when I deploy my react application on Vercel, server is giving 401 error Unauthorised.Not able to solve this Can anybody help?

**Comment by pratham947** [comment]
@SAM-BOGHARA can you please explain how you can deploy judge0 on ec2 i am getting several errors in it

**Comment by marcgabe15** [comment]
has anyone gotten it to work on an amazon linux instance? I can only get it working on Ubuntu 22.x instances.

**Comment by harsiddhdave44** [comment]
> has anyone gotten it to work on an amazon linux instance? I can only get it working on Ubuntu 22.x instances.

@marcgabe15 It works only on Ubuntu instances. It's mentioned in the documentation as well.
