### ISSUE TITLE
how to output file

### ISSUE THREAD

**Issue by freew01f** [judge0/judge0#263]
If some code depends on sone raw data such as csv file 
can I use additional_files as the input file? what is the file path?
and 
how can I output file form the code, how to get the path ?

**Comment by hermanzdosilovic** [comment]
Please watch [this Asciicast](https://asciinema.org/a/318548) that should answer your question.

**Comment by freew01f** [comment]
> Please watch [this Asciicast](https://asciinema.org/a/318548) that should answer your question.

Thanks very much.
