### ISSUE TITLE
/workers always returning an empty array

### ISSUE THREAD

**Issue by ragrag** [judge0/judge0#264]
running on the latest release, /workers seems to always return an empty array.

tried with the default setting (2*nproc) as well as setting manual numbers of workers.

**Comment by hermanzdosilovic** [comment]
Try first running some submissions and then check the number of worker.

**Comment by ragrag** [comment]
> Try first running at least one submission and then check the number of workers. See #124

Thank you so much, running a submission from the dummy client made it work. However, even though the code executed successfully it shows that the number of workers is 0, is this an intended behavior for 2*nproc workers?

**Comment by hermanzdosilovic** [comment]
That is not intended behaviour, it might be a bug that is connected with the https://github.com/judge0/judge0/issues/256. I need to take a closer look before next release.
