### ISSUE TITLE
Unable to run testcases with output size greater than 1MB

### ISSUE THREAD

**Issue by rajchandra3** [judge0/judge0#269]
When I run a testcase with the size of the output `>1 MB`, I get this error 
```
OSError: [Errno 27] File too large
```
Language: Python3 (code `71`)

Is there a way to fix this?
Lmk if you need any other information.

**Comment by hermanzdosilovic** [comment]
Take a look at the [`max_file_size`](https://ce.judge0.com/#submissions-submission).

**Comment by rajchandra3** [comment]
thanks a ton, solved!
