### ISSUE TITLE
Extra characters in python output

### ISSUE THREAD

**Issue by rajchandra3** [judge0/judge0#270]
When running a code in python(`71`), the output contains an extra line. Is this something done on purpose?

expected :
```
15
```

returned output from judge0
```
15

```

**Comment by hermanzdosilovic** [comment]
Hi,
what code are you running?

**Comment by rajchandra3** [comment]
@hermanzdosilovic as simple as "hello world" on [ide.judge0.com](ide.judge0.com), same happens on our hosted server as well.
![image](https://user-images.githubusercontent.com/25290995/114286746-25c31c80-9a7f-11eb-9d75-8f000b1bb1f1.png)

**Comment by rajchandra3** [comment]
@hermanzdosilovic is there anything you can suggest for me to fix this?

**Comment by hermanzdosilovic** [comment]
Take a look at the docs for Python's print function. https://docs.python.org/3.8/library/functions.html#print

Fix for this "problem" is the following code:
```
print("hello, world", end="")
```

**Comment by rajchandra3** [comment]
Makes sense, thanks.
