### ISSUE TITLE
Upstream closes connection abruptly for large testcases batch submission

### ISSUE THREAD

**Issue by rajchandra3** [judge0/judge0#271]
I have an Nginx as a proxy server, and I made a batch request with 6 testcases of sizes as follows
- first two testcases of sizes less than 1MB
- next 4 testcases with input size = output size = 6MB

It takes more than 80-120 seconds to return the response and that too the response is empty. 

I have two questions:
1. Why does it take so long? Is there anything I can do to make it fast (Using 4GB / 2 CPUs, 80 GB SSD Disk)
2. Is there a way to fix the error below?

```
2021/04/13 19:58:55 [error] 534157#534157: *1170 upstream prematurely closed connection while reading response header from upstream, client: **.**.**.**, server:example.com, request: "POST /submissions/batch?base64_encoded=true&wait=false HTTP/1.1", upstream: "http://127.0.0.1:2358/submissions/batch?base64_encoded=true&wait=false", host: "example.com"
```

I have deployed version `1.13.0`

**Comment by rajchandra3** [comment]
Here is my `nginx.conf` file if thay helps.
```
user root;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules_enabled/*.conf;

events {

}

http {
        include /etc/nginx/mime.types;
        #main block of configs
        server {
                server_name example.com;                         
                proxy_read_timeout 1000;
                proxy_connect_timeout 1000;
                proxy_send_timeout 1000;
                proxy_max_temp_file_size 0;
                client_max_body_size 200m;
                location / {
                        proxy_pass http://localhost:2358/;
                }
        }
}
```

**Comment by rajchandra3** [comment]
@hermanzdosilovic any help?

**Comment by hermanzdosilovic** [comment]
Hi @rajchandra3,

What happens if you do this directly and not through the proxy?

**Comment by rajchandra3** [comment]
I tried deploying without Nginx and now I observed the server responds with `socket hang up`. I am running a nodejs app that makes a request to the deployed judge0 APIs. Let me know if you need any more information.

Another observation is that, after setting up the server, for the first 10 requests that I made, 4 worked fine and 6 failed, after that none of the requests are working.

**Comment by rajchandra3** [comment]
@hermanzdosilovic does judge0's EE edition come with support or Is it just going to be like this where the customers are going to be hung up with their issues?

I was testing it out on my own to see features and the use cases but looks like the support is not good for the service, lmk if EE has better support.

**Comment by TringBala** [comment]
> I have an Nginx as a proxy server, and I made a batch request with 6 testcases of sizes as follows
> 
> * first two testcases of sizes less than 1MB
> * next 4 testcases with input size = output size = 6MB
> 
> It takes more than 80-120 seconds to return the response and that too the response is empty.
> 
> I have two questions:
> 
> 1. Why does it take so long? Is there anything I can do to make it fast (Using 4GB / 2 CPUs, 80 GB SSD Disk)
> 2. Is there a way to fix the error below?
> 
> ```
> 2021/04/13 19:58:55 [error] 534157#534157: *1170 upstream prematurely closed connection while reading response header from upstream, client: **.**.**.**, server:example.com, request: "POST /submissions/batch?base64_encoded=true&wait=false HTTP/1.1", upstream: "http://127.0.0.1:2358/submissions/batch?base64_encoded=true&wait=false", host: "example.com"
> ```
> 
> I have deployed version `1.13.0`

@rajchandra3 How you passing the custom testcases in junge0, currently Im used this for compilation only?. Any Idea Pls?.

**Comment by TringBala** [comment]
@hermanzdosilovic Hi,
Do you have any Idea how can I pass the custom testcase execution for the program using judge0?.
