### ISSUE TITLE
C++ string.find() always returns string::npos

### ISSUE THREAD

**Issue by Fromnowon** [judge0/judge0#272]
I use judge0 to run c++ code and encounter a problem.

```cpp
#include<iostream>
#include<cstring>
#include<string>
#include<algorithm>
using namespace std;

int main()
{
    string s1, s2;
    getline(cin, s1), getline(cin, s2);
    cout << s1 << endl << s2 << endl;
    cout << s2.find(s1) << endl;

    return 0;
}
```
```
input: 
aa
aaaaa
output:
aa
aaaaa
18446744073709551615
```
It means not found.
Then I change the code like this:
  ```cpp
// ...
cout << s2.find("aa") << endl;
// ...
```
It returns 0, which means find "aa" in "aaaaa" at index 0.

I have tested in Visual Studio 2019 and it doesn't have this issue.

And if code is
```cpp
#include<iostream>
#include<cstring>
#include<string>
#include<algorithm>
using namespace std;

int main()
{
    string s1 = "aa", s2 = "aaaaaa";
    // getline(cin, s1), getline(cin, s2);
    cout << s1 << endl << s2 << endl;
    cout << s2.find(s1) << endl;

    return 0;
}
```
Everything is ok. Maybe there is something wrong with "getline"?

**Comment by hermanzdosilovic** [comment]
Hi @Fromnowon,

I cannot reproduce your issue:
![image](https://user-images.githubusercontent.com/7927278/115122962-1847ee00-9fbb-11eb-9664-2d6a9e7691de.png)

I used a widget on https://judge0.com on Linux inside Google Chrome.

**Comment by Fromnowon** [comment]
@hermanzdosilovic Thanks for replying!
I tried the widget and it did run perfectly.
But I copied the codes and ran in https://ide.judge0.com/, it returned me 18446744073709551615.

![image](https://user-images.githubusercontent.com/2792725/115129832-1f531880-a01c-11eb-9e7c-26410d2432ae.png)

I tried to checkout the post data but found no difference.

![image](https://user-images.githubusercontent.com/2792725/115129865-8375dc80-a01c-11eb-8e27-b0370c76fa02.png)

**Comment by Fromnowon** [comment]
In fact The ```stdin``` of two editors are different.
I get to know what the problem is.
The stdin should have a '\n' in the end.

![image](https://user-images.githubusercontent.com/2792725/115130302-57108f00-a021-11eb-8f1b-3da93a51014c.png)

Thanks for @hermanzdosilovic helping me!
