### ISSUE TITLE
[Question]  "Python for ML" and some language not working in docker?

### ISSUE THREAD

**Issue by anubhabmondalDirac** [judge0/judge0#277]
Hi sir,
 I deploy judge0 using docker. But I notice few languages (like "Python for ML") not working. Is there any way I can compile and run those languages? I am currently using "judge0-v1.12.0-https".
 Thanks in advanced. @mejibyte @cesar @vvalchev @hermanzdosilovic

**Comment by hermanzdosilovic** [comment]
Python for ML is in [Judge0 Extra CE](https://judge0.com/extra-ce). Please read [the supported languages section from the README](https://github.com/judge0/judge0#supported-languages).

**Comment by anubhabmondalDirac** [comment]
Thanks @hermanzdosilovic
