### ISSUE TITLE
How to user input in JavaScript

### ISSUE THREAD

**Issue by LinardsLiepenieks** [judge0/judge0#279]
Hi
I'm using Judge0 api. What do you need to write in code for stdin.
I'm looking for the equivalent of C++ Cin>> or pythons input()

**Comment by hermanzdosilovic** [comment]
Unfortunately, I am not familiar with JavaScript so much that I can tell you how to read user's input.

**Comment by anilmaurya** [comment]
@LinardsLiepenieks 

I used following code snippet
```
function myFunction(item, index){
              // Write your code here

              // console.log(output)
 }

  process.stdin.on('data', data => {
              // Convert string array to integer array
              var input_array = data.toString().split(',').map(i => Number(i));
              myFunction(input_array)
 })
