### ISSUE TITLE
wait parameter not working in batch submission

### ISSUE THREAD

**Issue by ajay-staruss** [judge0/judge0#280]
I have used wait=true in submission to get synchronous data, but using wait=true does not work in batch submit. Please help me as soon as possible, its urgent

**Comment by freew01f** [comment]
I do not think batch submission support wait 
u can see the doc

**Comment by hermanzdosilovic** [comment]
@ajay-staruss `wait=true` i.e. synchronous submission creation **does not** work with batched submissions.

**Comment by ajay-staruss** [comment]
Okay thanks, I created a workaround on it. Will update my system when you will release v1.14
