### ISSUE TITLE
how can i enable swift lang

### ISSUE THREAD

**Issue by freew01f** [judge0/judge0#281]
I want to try swift lang 
how can i enable it 
thanks

**Comment by hermanzdosilovic** [comment]
Swift is available via [Judge0 CE](https://judge0.com/ce) under [language ID 83](https://ce.judge0.com/languages/83).

Here is a simple `hello, world` program in Swift:
```swift
import Foundation
print("hello, world")
```

**Comment by freew01f** [comment]
ok thanks very much
I do not find it in the language list
