### ISSUE TITLE
Correct way to configure Judge0 for large number of requests

### ISSUE THREAD

**Issue by parasjindal** [judge0/judge0#286]
Hi, I am using Judge0v1.13.0 on Azure VM with 2 processors and 8GB ram.
When sending **1 batch request** to that server, compilation and execution takes around **3 seconds overall.**
When sending **2 batch requests** from different machines to the same route, it takes almost double that is **6 seconds for each request** to complete.

Can someone guide on how to configure Judge0 correctly to run these requests in parallel?
Is there any guidance on what are the minimum requirements of server for Judge0 to work correctly?
If there are 50 parallel calls expected to Judge0, how can we support that efficiently?

**Comment by hermanzdosilovic** [comment]
Hi take a look at #118.
