### ISSUE TITLE
Judge0 ERR_CONNECTION_TIMED_OUT in AWS Lightsail

### ISSUE THREAD

**Issue by kznmdevelop** [judge0/judge0#287]
I'm Deploying v1.13.0-extra in AWS Lightsail Instance (8 GB RAM, 2 vCPUs, 160 GB SSD), and it doesn't works...

I connected to http://my_ip and it shows ERR_CONNECTION_TIMED_OUT error

80 Port is opened, UFW is inactive

whats problem?

**Comment by hermanzdosilovic** [comment]
Hi @kznmdevelop,

Unfortunately, I am not familiar with the AWS Lightsail but lets us keep this issue open for others to see.

**Comment by N0v0cain3** [comment]
@kznmdevelop

 https://github.com/judge0/judge0/blob/2e5faf8175ff529e04ef123899825fe8161dd4b4/docker-compose.yml#L16

If you're using ```docker-compose```,  did you try to open it on port 2358? http://my_ip:2358

**Comment by kznmdevelop** [comment]
Works that way! And I also found another way, setting docker compose setting with 80:2358

Thank you!
