### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Hunghus** [judge0/judge0#288]
I can't find any documentation to install.
i bought the package but 8 days no support.

**Comment by hermanzdosilovic** [comment]
Hi @Hunghus,

On Aug 24 you have asked a question on the Discord server and on the same day I have contacted you via PM asking you how exactly I can help you and I also asked for your RapidAPI username. Two days later you have answered me "i can't develop with it", after which on the same day I have instructed you to schedule a meeting with me at https://meet.judge0.com.

Please, schedule a meeting with me at https://meet.judge0.com. That is the fastest and easiest way for me to understand what is the problem and how can I help you.

Thank you.

Best regards,
Herman
