### ISSUE TITLE
How does judge0 deal with the problem of special judge?

### ISSUE THREAD

**Issue by iamwinter** [judge0/judge0#291]
Thank authors for developing this very useful project.

I have a question about how to deal with special judge. Specifically, there is a problem expecting the output with a decimal and if its output is different with standard output less than `0.001`, then the solutions would be consider as `Accepted`. 

For example, there is a problem with standard output `3.1415926`. It should returns `Accepted` if the solution executes and outputs `3.142` because `|3.1415926-3.142|=0.0004074<0.001`. In a similar way, it should returns `Wrong answer` if the solution executes and outputs `3.14` because `|3.1415926-3.14|=0.0015926>0.001` where abslute difference out of allowed range.

I look forward to your answer to my question. Thank you!

**Comment by techie-delight** [comment]
I'm not author, but you can tweak the compiler's output to match your requirements. What you can do is handle this in Javascript, after getting API response.

**Comment by iamwinter** [comment]
Thank you @coolph007 . I understood your method.

By the way, *Special Judge* is common in some algorithm sites and contests, such as [Codeforces](http://codeforces.com), [ICPC](https://icpc.global/) and so on. A problem maybe has not an unique answer instead of a standard unique answer. [Codeforces](http://codeforces.com) allows problem creator provides a custom program to compare differences of solution outputs and standard outputs.

For another example, A problem require solution to output a set which can be in any order. 
+ solution output
```
1 2 3 4 5
```
+ standard output
```
5 4 3 2 1
```
It's obvious that two outputs are equals when consider them as sets. Therefore, *solution outptu* is `Accepted`.
In order to complete this function, I can write a program (For convenience, use python) below to complete the comparation of solution output and standard output.
```python
def compare(solution_output, standard output):
    a = set(solution_output)
    b = set(stanard_output)
    if a == b:
        return "Accepted"
    else:
        return "Wrong Answer"
```

When I send a request to judge0, I would like to provide a custom program like above to complete comparation of outputs. Could judge0 do it? Thanks!

**Comment by MouadBNL** [comment]
> Thank you @coolph007 . I understood your method.
> 
> By the way, _Special Judge_ is common in some algorithm sites and contests, such as [Codeforces](http://codeforces.com), [ICPC](https://icpc.global/) and so on. A problem maybe has not an unique answer instead of a standard unique answer. [Codeforces](http://codeforces.com) allows problem creator provides a custom program to compare differences of solution outputs and standard outputs.
> 
> For another example different from [the first comment](https://github.com/judge0/judge0/issues/291#issue-993095321), A problem requires solution to output a set which can be in any order.
> 
> * solution output
> 
> ```
> 1 2 3 4 5
> ```
> 
> * standard output
> 
> ```
> 5 4 3 2 1
> ```
> 
> It's obvious that two outputs are equals when considering them as sets. Therefore, _solution output_ is `Accepted`.
> In order to complete this function, I can write a program (For convenience, use python) below to complete the comparation of solution output and standard output.
> 
> ```python
> def compare(solution_output, standard output):
>     a = set(solution_output)
>     b = set(stanard_output)
>     if a == b:
>         return "Accepted"
>     else:
>         return "Wrong Answer"
> ```
> 
> When I send a request to judge0, I would like to provide a custom program like above to complete comparation of outputs. Could judge0 do it? Thanks!

You can just run the verification code in another submission, you send the first submission with no expected output, then send the verification code as another submission with the expected output and the output of the first submission.

**Comment by iamwinter** [comment]
@MouadBNL Thanks!
