### ISSUE TITLE
Can files in `additional_files` be readable?

### ISSUE THREAD

**Issue by iamwinter** [judge0/judge0#292]
*[single-file-programs](https://ce.judge0.com/#header-single-file-programs)* provides a way to add extra module in python or header files in C/C++. Could I send one or some text files using that way and then my program read them?

For example, except `stdin`, my program has to read a extra text file named `help.txt` with custom content like below
```
apple
banana
water
...
```

1. How to send the extra file.
2. Can my program read the extra file using *File Reader API*?

**Comment by iamwinter** [comment]
Solved.
I found [Multi-file programs](https://ce.judge0.com/#header-multi-file-programs) could finished the requirement.

**Comment by hermanzdosilovic** [comment]
Hi @iamwinter,

yes, files in `additional_files` can be readable. Take a look at this example: https://asciinema.org/a/318548

**Comment by iamwinter** [comment]
> Hi @iamwinter,
> 
> yes, files in `additional_files` can be readable. Take a look at this example: https://asciinema.org/a/318548

Thanks!
