### ISSUE TITLE
Scaling the Judge0 Server

### ISSUE THREAD

**Issue by yashrsharma44** [judge0/judge0#302]
Hi @hermanzdosilovic 

Thanks for the awesome setup, I read through bunch of issues, and learnt a lot about scaling Judge0.

I had gone through bunch of issues, #226 #118 #211 #166 and found some useful discussions for scaling Judge0 setup. I was curious about scaling the Judge0 _master_ server, is there any way to scale the Judge0 server instance?

Since, this would be the single source of failure for the Judge0 OJ, I was wondering, if there are any strategies for scaling the same?

**Comment by hermanzdosilovic** [comment]
Hi @yashrsharma44,

yes, it is possible to scale both servers and workers, but I don't provide any instructions or support for that since it is our business model to sell Judge0 as SaaS. The only thing I can say to you is that in production we scale both.
