### ISSUE TITLE
Way to find Test Case API

### ISSUE THREAD

**Issue by IndrajeetS** [judge0/judge0#303]
Hi Team, 

I have been working on my college project and I am unable to find API, which accepts **Test case**, can someone please help me with that.

- I have been using Create Submission API - POST https://ce.judge0.com/submissions/?base64_encoded=false&wait=false
- I tried to use Submission Batch API - POST https://ce.judge0.com/submissions/batch?base64_encoded=false

Any help is appreciated, Thank you 🤓😇

**Comment by alpha5555** [comment]
http://ip:2358/docs

**Comment by hermanzdosilovic** [comment]
Hi @IndrajeetS,

when you create a submission with Judge0 it allows you to create just one input/expected output pair i.e. test case.

If your problem has multiple test cases, then you should create a batched submission that allows you to create multiple submissions with one request.

Please, let me know if you have any other questions.

**Comment by WissdaDigital** [comment]
Hi @hermanzdosilovic ,
Firstly, I would like to thank you for such an amazing product.
I have few queries which I would feel delighted if they are resolved:
1. Post request to  https://ce.judge0.com/submissions/batch?base64_encoded=false - gets me Unauthorized (401). I dont see any authorization that has to be added from the documentation, but I am unsure where I am going wrong.
2. Is testing multiple test cases for the same code base (multiple stdin and expected_output) version released? And is it available open source?

Would be very much thankful for your help

**Comment by Ananthalakshmii** [comment]
Hi @hermanzdosilovic ,
Firstly, I would like to thank you for such an amazing product.
I have few queries which I would feel delighted if they are resolved:

1.Post request to https://ce.judge0.com/submissions/batch?base64_encoded=false - gets me Unauthorized (401). I dont see any authorization that has to be added from the documentation, but I am unsure where I am going wrong.

2.Is testing multiple test cases for the same code base (multiple stdin and expected_output) version released? And is it available open source?

Would be very much thankful for your help
