### ISSUE TITLE
How does Judge0 run Python code? 

### ISSUE THREAD

**Issue by farahmand-m** [judge0/judge0#308]
Hey there.

I'm working on a small system for automating students Python script grading. I was hoping to take some inspiration from how Judge0 isolates Python code while still providing it with a few pre-installed libraries efficiently but I couldn't find anything about this in the documentation.

I'd appreciate your help if you could elaborate on your method. Do you run the codes inside Docker? I've heard that's secure but highly inefficient.

**Comment by hermanzdosilovic** [comment]
Hi @farahmand-m, you can read more about it here https://github.com/judge0/compilers.
