### ISSUE TITLE
Getting error No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by alaksandarjesus** [judge0/judge0#311]
Hi,

I installed Extra CE from https://github.com/judge0/judge0/blob/extra/CHANGELOG.md#deployment-procedure

As per documentation the application is accessible from 

Your instance of Judge0 Extra CE v1.13.0 is now available at http://IP ADDRESS OF YOUR SERVER.

But my application is accessible from http://IP ADDRESS OF YOUR SERVER:2358

![image](https://user-images.githubusercontent.com/4712552/146179010-d7319fc8-837b-4265-9993-d115861a4717.png)

When i submit the code, which was working with ce version, i am getting 

----------------- Message For Input 1 ---------------
No such file or directory @ rb_sysopen - /box/script.py
---------------------------------------------------
----------------- Message For Input 2 ---------------
No such file or directory @ rb_sysopen - /box/script.py
---------------------------------------------------

![image](https://user-images.githubusercontent.com/4712552/146179093-183e188a-9964-4c46-ab25-9b3646d6b998.png)

![image](https://user-images.githubusercontent.com/4712552/146179227-f107120e-401d-4d6b-8124-b8bddc8e677f.png)

Its a fresh new Ubuntu Server 21.10 and no other applications are running. Please let us know if we are missing any library.

We are trying to hit python for ML with language id 10. It works fine on ide.judge0.com.

To add more info the given payload is

http://xxx:2358/submissions?base64_encoded=true&wait=false

{"command_line_arguments": "",
"compiler_options": "",
"language_id": 10,
"redirect_stderr_to_stdout": false,
"source_code": "cHJpbnQoIkhlbGxvIFdvcmxkIikKZGVmIGFsYWtzKCk6CiAgcHJpbnQoIkhlbGxvIFdvcmxkIikKYWxha3MoKQ==",
"stdin": ""}

![image](https://user-images.githubusercontent.com/4712552/146181877-9dda0fdd-ea8b-4461-a557-f2f22670eb73.png)

And response is

{
  "stdout": null,
  "time": null,
  "memory": null,
  "stderr": null,
  "token": "31e2e06d-aeb0-46e7-8b88-a4df987d4165",
  "compile_output": null,
  "message": "Tm8gc3VjaCBmaWxlIG9yIGRpcmVjdG9yeSBAIHJiX3N5c29wZW4gLSAvYm94\nL3NjcmlwdC5weQ==\n",
  "status": {
    "id": 13,
    "description": "Internal Error"
  }
}

![image](https://user-images.githubusercontent.com/4712552/146182125-f65df4b9-dbff-4950-803e-5d9f30c87867.png)

**Update 1:**
Made new ubuntu installation 20.04 it works as expected.

**Comment by alifanantomi** [comment]
Hi, I get the same error every time i try to get the submission. Alredy check the syntax I submit but still didn't work as it should be. I use macOS. How I fix it?

**Comment by phamngocquy** [comment]
I'm getting the same error when running on my local machine (docker - macOS).
But it's still no problem when I run up on the ubuntu server.

**Comment by hermanzdosilovic** [comment]
This problem is related to https://github.com/judge0/judge0/issues/325

Use Ubuntu 20.04 or if on macOS then follow instructions from #325.
