### ISSUE TITLE
multifile program error No such file or directory @ rb_sysopen - /box/additional_files.zip'

### ISSUE THREAD

**Issue by kimutaiRop** [judge0/judge0#315]
I am getting the error when submitting multifile program 
```json

{'stdout': None, 'time': None, 'memory': None, 'stderr': None, 'token': '6d1568c5-9b6b-4c6f-8e8b-5b82f6bf79c3', 'compile_output': None, 'message': 'No such file or directory @ rb_sysopen - /box/additional_files.zip', 'status': {'id': 13, 'description': 'Internal Error'}}

```

```python
    URL = f"http://127.0.0.1/submissions"

    querystring = {
                   "wait": "true",
                   "fields": "stdout,time,memory,stderr,token,compile_output,message,status"}
 
    payload = {
        "language_id": language_id,
        "additional_files": source_code,
    }
    headers = {
        'content-type': "application/json",
    }

    response = requests.request("POST", URL, data=json.dumps(payload), headers=headers, params=querystring)
    return response
```

my `source_code` is base64 string of the zip folder encoded and `language_id` is 89 what could I be doing wrong?

submitting to the server in rapidapi works fine though but failing in all my computers whenever I build using docker

**Comment by phamngocquy** [comment]
I'm getting the same error when running on my local machine (docker - macOS).
But it's still no problem when I run up on the ubuntu server.

**Comment by hermanzdosilovic** [comment]
This issue is probably linked with this one https://github.com/judge0/judge0/issues/325. As mentioned there, I would suggest that you try enabling cgroups v1 in GRUB configuration settings.

**Comment by phamngocquy** [comment]
if need run only judge worker, better we using ubuntu 20.04 to set up and scale
