### ISSUE TITLE
No such file or directory @ rb_sysopen - /box/Main.java

### ISSUE THREAD

**Issue by jothiprakashv** [judge0/judge0#323]
Getting this error after submission.

![image](https://user-images.githubusercontent.com/37209089/155068693-9a26f031-e36f-4758-873e-f8a75ab288a4.png)

**Comment by jothiprakashv** [comment]
We are running judge0 in VPS server Ubuntu 18.04 LTS.

this is our docker-compose.yml file

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  server:
    image: judge0/api:1.8.0
    volumes:
      - ./judge0-api.conf:/judge0-api.conf:ro
    ports:
      - "8899:3000"
    <<: *default-logging
    restart: always

  workers:
    image: judge0/api:1.8.0
    command: ["./scripts/workers"]
    volumes:
      - ./judge0-api.conf:/judge0-api.conf:ro
    <<: *default-logging
    restart: always

  db:
    image: postgres:9.6
    env_file: judge0-api.conf
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:4.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0-api.conf
    volumes:
      - ./srv/redis-data:/data
    <<: *default-logging
    restart: always

**Comment by jothiprakashv** [comment]
We are stuck here. Any help is much appreciated.

**Comment by hermanzdosilovic** [comment]
This issue is related to this one https://github.com/judge0/judge0/issues/325.

**Comment by hermanzdosilovic** [comment]
Hi @karansojitra-trootech,

Please use the script in the attachment and run it like this: `sudo ./update-grub.sh`.

[update-grub.sh](https://github.com/user-attachments/files/22969839/update-grub.sh)

**Comment by karansojitra-trootech** [comment]
> Hi [@karansojitra-trootech](https://github.com/karansojitra-trootech),
> 
> Please use the script in the attachment and run it like this: `sudo ./update-grub.sh`.
> 
> [update-grub.sh](https://github.com/user-attachments/files/22969839/update-grub.sh)

@hermanzdosilovic 

The File you provided, I have executed that file. 

Docker is up and ready to work, but When Executing APIs, I'm finding this issue. 

I'm attaching screenshots for the same.

### Output from API
<img width="1244" height="637" alt="Image" src="https://github.com/user-attachments/assets/9d1e80eb-857b-4588-8c63-8b2bbd6c2e2d" />

### Docker logs
<img width="1717" height="639" alt="Image" src="https://github.com/user-attachments/assets/8777c2cb-b22d-4b9d-bc7f-af20957e9f4f" />
