### ISSUE TITLE
Tensorflow current problem

### ISSUE THREAD

**Issue by bangoc123** [judge0/judge0#341]
Hi team,

When using the current version of TensorFlow, the system through an exception when its sub library - protobuf was upgraded.

The error looks like this: 

```
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

```

To fix this, please downgrade the version of protobuf package to `3.20.x or lower`.

Thanks.

**Comment by hermanzdosilovic** [comment]
Hi @bangoc123,

thank you for this. The problem has been resolved.
