### ISSUE TITLE
empty response on localhost

### ISSUE THREAD

**Issue by ahmedgroup1989** [judge0/judge0#351]
I installed docker and installed judge0 as mentioned in the install doc but it gives empty page when open localhost
Steps done in installing : 
With HTTP
Install [Docker](https://docs.docker.com/) and [Docker Compose](https://docs.docker.com/compose).
Download and extract the release archive:
wget https://github.com/judge0/judge0/releases/download/v1.13.0/judge0-v1.13.0.zip
unzip judge0-v1.13.0.zip
Run all services and wait a few seconds until everything is initialized:
cd judge0-v1.13.0
docker-compose up -d db redis
sleep 10s
docker-compose up -d
sleep 5s
Your instance of Judge0 CE v1.13.0 is now available at http://<IP ADDRESS OF YOUR SERVER>:2358.

**Comment by ahmedgroup1989** [comment]
![image](https://user-images.githubusercontent.com/109882766/180627836-d6a6b0c3-bf35-4b4a-8ed6-4890bf682691.png)

**Comment by ahmedgroup1989** [comment]
![image](https://user-images.githubusercontent.com/109882766/180627962-b6a49e14-8a2a-48ea-a45f-c8ee98dc0255.png)

**Comment by JohnPremKumar** [comment]
Yes. By default home page it empty. Visit localhost:2358/docs for documentation page.

**Comment by ahmedgroup1989** [comment]
> Yes. By default home page is empty. Visit localhost:2358/docs for documentation page.

How to view the IDE

**Comment by ahmedgroup1989** [comment]
> > Yes. By default home page is empty. Visit localhost:2358/docs for documentation page.
> 
> How to view the IDE

I have fixed that by installig the IDE (https://github.com/judge0/ide) and changing the API path
