### ISSUE TITLE
Need to run judge0 without using docker 

### ISSUE THREAD

**Issue by ahmadhaidarahmad** [judge0/judge0#353]
I was not able to run judge0 project without using the docker image judge0 in the docker compose. I need to run the project on the machine os directly, I’m using ubuntu. 
Any  help would be appreciated Thank you 🙏

**Comment by hermanzdosilovic** [comment]
Hi @ahmadhaidarahmad,

unfortunately, at this point in time, Judge0 has been so Docker dependent that I don't know how exactly would you run it without it.

Best regards,
Herman

**Comment by ahmadhaidarahmad** [comment]
Thank you 🙏 @hermanzdosilovic
