### ISSUE TITLE
Why "Cannot run proxy, clone failed: Invalid argument" on macos 12.5 (Apple M1 Pro)

### ISSUE THREAD

**Issue by winterant** [judge0/judge0#360]
This is docker container log.
```
workers_1  | [2022-08-27T09:52:34+00:00] Compiling submission 9b1646a0-9bba-4065-bf9c-a5bbeafe918b (7):
workers_1  | isolate --cg -s -b 7 -M /var/local/lib/isolate/7/metadata.txt --stderr-to-stdout -i /dev/null -t 15.0 -x 0 -w 20.0 -k 128000 -p120 --cg-timing --cg-mem=512000 -f 4096 -E HOME=/tmp -E PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -E LANG -E LANGUAGE -E LC_ALL -E JUDGE0_HOMEPAGE -E JUDGE0_SOURCE_CODE -E JUDGE0_MAINTAINER -E JUDGE0_VERSION -d /etc:noexec --run -- /bin/bash compile > /var/local/lib/isolate/7/compile_output.txt 
workers_1  | 
workers_1  | [2022-08-27T09:52:34+00:00] Compiling submission 52501a30-a354-4d0c-bb3d-9c17402721cf (3):
workers_1  | isolate --cg -s -b 3 -M /var/local/lib/isolate/3/metadata.txt --stderr-to-stdout -i /dev/null -t 15.0 -x 0 -w 20.0 -k 128000 -p120 --cg-timing --cg-mem=512000 -f 4096 -E HOME=/tmp -E PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -E LANG -E LANGUAGE -E LC_ALL -E JUDGE0_HOMEPAGE -E JUDGE0_SOURCE_CODE -E JUDGE0_MAINTAINER -E JUDGE0_VERSION -d /etc:noexec --run -- /bin/bash compile > /var/local/lib/isolate/3/compile_output.txt 
workers_1  | 
workers_1  | Cannot run proxy, clone failed: Invalid argument
workers_1  | Cannot run proxy, clone failed: Invalid argument
```

**Comment by winterant** [comment]
```bash
zhao@Winterant judge0-v1.13.0 % curl -X POST -H "Content-Type: application/json" -d '{ "source_code": "echo hello, world", "language_id": 46 }' "localhost:2358/submissions" | jq -M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   105    0    48  100    57    349    414 --:--:-- --:--:-- --:--:--   813
{
  "token": "b65702a0-7ae0-43bf-82b8-c9b65e9cd857"
}
zhao@Winterant judge0-v1.13.0 % curl "localhost:2358/submissions/b65702a0-7ae0-43bf-82b8-c9b65e9cd857"|jq -M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   281    0   281    0     0   3648      0 --:--:-- --:--:-- --:--:--  4014
{
  "stdout": null,
  "time": "0.0",
  "memory": 0,
  "stderr": "Cannot run proxy, clone failed: Invalid argument\n",
  "token": "b65702a0-7ae0-43bf-82b8-c9b65e9cd857",
  "compile_output": null,
  "message": "Cannot run proxy, clone failed: Invalid argument",
  "status": {
    "id": 13,
    "description": "Internal Error"
  }
}
zhao@Winterant judge0-v1.13.0 % 
```

**Comment by winterant** [comment]
> ```
> workers_1  | [2022-08-27T09:52:34+00:00] Compiling submission 9b1646a0-9bba-4065-bf9c-a5bbeafe918b (7):
> workers_1  | isolate --cg -s -b 7 -M /var/local/lib/isolate/7/metadata.txt --stderr-to-stdout -i /dev/null -t 15.0 -x 0 -w 20.0 -k 128000 -p120 --cg-timing --cg-mem=512000 -f 4096 -E HOME=/tmp -E PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -E LANG -E LANGUAGE -E LC_ALL -E JUDGE0_HOMEPAGE -E JUDGE0_SOURCE_CODE -E JUDGE0_MAINTAINER -E JUDGE0_VERSION -d /etc:noexec --run -- /bin/bash compile > /var/local/lib/isolate/7/compile_output.txt 
> workers_1  | 
> workers_1  | [2022-08-27T09:52:34+00:00] Compiling submission 52501a30-a354-4d0c-bb3d-9c17402721cf (3):
> workers_1  | isolate --cg -s -b 3 -M /var/local/lib/isolate/3/metadata.txt --stderr-to-stdout -i /dev/null -t 15.0 -x 0 -w 20.0 -k 128000 -p120 --cg-timing --cg-mem=512000 -f 4096 -E HOME=/tmp -E PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -E LANG -E LANGUAGE -E LC_ALL -E JUDGE0_HOMEPAGE -E JUDGE0_SOURCE_CODE -E JUDGE0_MAINTAINER -E JUDGE0_VERSION -d /etc:noexec --run -- /bin/bash compile > /var/local/lib/isolate/3/compile_output.txt 
> workers_1  | 
> workers_1  | Cannot run proxy, clone failed: Invalid argument
> workers_1  | Cannot run proxy, clone failed: Invalid argument
> ```

This is the output of docker container log.

**Comment by Axel546** [comment]
I have the same problem! Did you find any solutions?

**Comment by winterant** [comment]
> I have the same problem! Did you find any solutions?

No. It seems because macbook pro m1 adopted architecture arm64 but docker image judge0 only built for amd64.  We can see the information at dockerhub (also see that at #361 ). So I had to run judge0 on a linux/amd64 computer while my macbook is able to connect using ip.

**Comment by Axel546** [comment]
Thank you! Would it be possible to Upload it to azure server (as far as I know they use Linux) and use it from there?

**Comment by winterant** [comment]
> Thank you! Would it be possible to Upload it to azure server (as far as I know they use Linux) and use it from there?

I didn't use a azure server. But I think you can run the command `arch` on azure server  to see what architechture it adopted. 
```bash
arch
```
If terminal outputs "amd64" or "x64_x86" but not "arm64", then it's OK to run judge0.

**Comment by hb1998** [comment]
enabling rosetta 2 in docker fixed the issue m1 macs 
![image](https://github.com/judge0/judge0/assets/33490801/b13949a9-8c14-4ffb-9efe-d1787a78a968)

**Comment by raju249** [comment]
Enabling rosetta2 resolved this error for me. 👍
