### ISSUE TITLE
Would judge0 support arm or arm64 architecture?

### ISSUE THREAD

**Issue by winterant** [judge0/judge0#361]
Dockerhub page shows that judge0 only supports architecture of linux/amd64. 
<img width="771" alt="image" src="https://user-images.githubusercontent.com/37205944/188298262-8dec4190-32fb-408d-9818-1882c37369c9.png">
Would it add other architecture into supportted list,  such as linux/arm64?

**Comment by PhilipJonasFranz** [comment]
I would greatly appreciate an official `arm` image, I tried building the images myself but it simply took too long.
