### ISSUE TITLE
cannot access '/box': No such file or directory

### ISSUE THREAD

**Issue by Axel546** [judge0/judge0#362]
I am trying to use the dockerized version of judge0 but I can't seem to make it work. Whenever I try it, I get this strange message "No such file or directory @ rb_sysopen - /box/...".

I am using a Macbook Pro with macOS Monterey version 12.5, apple M1 Pro chip.

I already tried to change deprecatedcgroupv1 but it still does not work. Any help would be highly appreciated.

**Comment by tsenguunchik** [comment]
Experiencing this as well
