### ISSUE TITLE
Using Judge0 in large-scale production

### ISSUE THREAD

**Issue by ryankwondev** [judge0/judge0#366]
Hi, thanks for start and maintaining this project.

I'm going to use Judge0 CE at large-scale production, will submit codes 100~300 codes per second.

In this case, can I use singe judge0 instance with just modifying worker amount?

If I can't, (when I have to scale-out judge0 instance) then can I share Postgres and Redis instance between instances?

**Comment by hermanzdosilovic** [comment]
Duplicate of #118
