### ISSUE TITLE
Better way to check statuses in batch submissions

### ISSUE THREAD

**Issue by hleytondiaz** [judge0/judge0#368]
Hi, when I send a batch submission the API returns the tokens. Then I have to check each token until there is no token with status 1 or 2 (in queue or processing). 

I’m doing that, because I keep a state in my own database when the submission has been completed.

My problem is that I have to check each token with a while loop setting a timeout.  I think that is not good for performance.

Is there a better way to do that?

**Comment by kdvkrs** [comment]
What about the `callback_url` parameter? This should also work for batch submissions afaik. You could wait until every submission has been processed and "called back" to your application.

**Comment by hleytondiaz** [comment]
Hi @kdvkrs 
I had not noticed that parameter, thank you very much!

**Comment by Kagenui-yozuru** [comment]
> What about the `callback_url` parameter? This should also work for batch submissions afaik. You could wait until every submission has been processed and "called back" to your application.

Hello, may I ask how the "callBack" from Judge0 is returned? Does it execute after all the submissions are completed or does it execute after each individual submission?
