### ISSUE TITLE
Could we update the python version

### ISSUE THREAD

**Issue by mazarady** [judge0/judge0#373]
The current Python version supported by judge0 is Python (3.8.1); however, this does not let me run the following code: 

```
def print_odd_numbers(list_of_numbers: list[int]) -> None:
  for number in list_of_numbers:
    if number % 2 != 0:
      print(number)
```

I receive the following error: 

```
Traceback (most recent call last):
  File "script.py", line 25, in <module>
    def print_odd_numbers(list_of_numbers: list[int]) -> None:
TypeError: 'type' object is not subscriptable
```

This is not an issue when you update the python version to >= 3.9.

**Comment by mazarady** [comment]
I resolved this issue by importing the following bit of code: `from __future__ import annotations`

**Comment by freew01f** [comment]
all the runtime are base on the base docker image
https://github.com/judge0/compilers
u can update every thing if u want
