### ISSUE TITLE
I create a SUBMISSION BATCH by javascript, I don't know where is the error? Please help me

### ISSUE THREAD

**Issue by minhduc0512** [judge0/judge0#374]
// This is my code
// Error: "there should be at least one submission in a batch"
const BASE_URL = "My judge0 server";
	const CPP_KEY = "53";
	let code = `#include <iostream>
using namespace std;
  int main() {
      int a,b;
	  cin >> a >> b;
	  cout<<a+b; \n
}`;
	var testcase = [];	  
	testcase.push({'input':'2 3','output':5});
	testcase.push({'input':'7 9','output':16});
	testcase.push({'input':'11 9','output':20});

	submissions = [];
	$.each(testcase,function(index,item){
		submission = {
			source_code: code,
			language_id: CPP_KEY,
			number_of_runs: "1",
			stdin: item.input,
			expected_output: item.output,
			cpu_time_limit: "2",
			cpu_extra_time: "0.5",
			wall_time_limit: "5",
			memory_limit: "128000",
			stack_limit: "64000",
			max_processes_and_or_threads: "60",
			enable_per_process_and_thread_time_limit: false,
			enable_per_process_and_thread_memory_limit: false,
			max_file_size: "1024"
		};
		submissions.push(submission);
	});
	let request = $.ajax({
		url: BASE_URL,
		type: "post",
		data: {'submissions':submissions},
	});

**Comment by WhosthatAoli** [comment]
Have you fix this?
