### ISSUE TITLE
Java Time Limit Exceeded Error

### ISSUE THREAD

**Issue by yeshwanth619** [judge0/judge0#380]
Hi,
I am passing below java code to my docker Judge0.

public class Main { 
 public static void main(String[] args) {   
 int i = 1; 
   while (i >0){
      System.out.println(i);   
 }  
  }
} 

It should return me time Limit Exceeded Error directly but, first it showing me processing error and then it is throwing the time limit exceeded error .  Please find the attached error for reference . 

![judge0 error](https://user-images.githubusercontent.com/39647143/204198888-5cff6e09-bb9e-46a5-ab76-d4dae8407b7e.png)

When I am integrating it with my **frontend** and calling this api I am getting response of **processing error** not the **time limit exceeded error** . Can anyone please help me to resolve this issue.

**Comment by hermanzdosilovic** [comment]
You are not getting a processing error but rather the state of the submission, which is "Processing". Submissions goes from state "In Queue" to "Processing", and then to any other state which is the result of its execution.

**Comment by yeshwanth619** [comment]
Thanks . Issue got resolved

**Comment by codeprepai** [comment]
Hi @yeshwanth619 , Can please let me know what you did here to solve this issue!
