### ISSUE TITLE
cpu time limit exceeded

### ISSUE THREAD

**Issue by yeshwanth619** [judge0/judge0#381]
Hi ,
 I am using below code in my Judge0 docker .
public class Main {
  public static void main(String[] args) {
     long i = 1;
    while (i <500000000) {
      System.out.println(i);
i++;
    }  
  }
}

I am using cpu time limit of 15 which is maximum if I increase it it's throwing an error and extra time as 10 .

When I run the code I am getting below error.
{
   "time": "15.018",
    "memory": 68972,
    "stderr": null,
    "token": "7059c324-82c0-46ef-a676-c89d5f8090ae",
    "compile_output": null,
    "message": "Time limit exceeded",
    "status": {
        "id": 5,
        "description": "Time Limit Exceeded"
    }
}

Could you please help me with this issue?

**Comment by yeshwanth619** [comment]
HI @denishotii  
I changed the modifications recommended by you in the docker judge0.config file as well as in settings but still I am getting the same error .
Could you please help me with it?

**Comment by yeshwanth619** [comment]
Thanks, Issue got resolved from discord

**Comment by Agrawal05** [comment]
Hi @yeshwanth619,
Could you please help me in this cpu_time_limit error?
I need to understand that how it is working.

I am using below code in my Judge0.
import time

def main():
# Start time
start_time = time.time()

# Loop indefinitely until 2 seconds have passed
while True:
    # Check if 10 seconds have passed
    if time.time() - start_time >= 10:
        break

# Print a message after 2 seconds have passed
print("Two seconds have passed!")
if name == "main":
main()

and I'm sending payload to judge0 submissions api :
{
"source_code": "import time\n\ndef main():\n # Start time\n start_time = time.time()\n\n # Loop indefinitely until 2 seconds have passed\n while True:\n if time.time() - start_time >= 10:\n break\n\n # Print a message after 2 seconds have passed\n print("Two seconds have passed!")\n\nif name == "main":\n main()",
"language_id": 71,
"stdin": "",
"expected_output": "Two seconds have passed!",
"cpu_time_limit": 15,
"memory_limit": 5000,
"max_file_size": 100,
"contest_id": "1",
"question_id": 11
}

When I run the code I am getting below error.
{
"stdout": "Two seconds have passed!\n",
"time": "9.867",
"memory": 3272,
"stderr": null,
"token": "2289dfc3-cd54-4288-a849-8b0ca77a035e",
"compile_output": null,
"message": "Time limit exceeded (wall clock)",
"status": {
"id": 5,
"description": "Time Limit Exceeded"
}
}
}

Could you please help me with this issue? I want to know how cpu_time_limit is working and will it also work properly on value below than 2 ?

**Comment by codeprepai** [comment]
@yeshwanth619 Hey, Can you please tell us What configuration you used.Thanks!
