### ISSUE TITLE
Batch submission API returns null for all the tokens

### ISSUE THREAD

**Issue by niteshrawat1995** [judge0/judge0#392]
Calling batch submission API with tokens returns `null` for each token. 
Things to notice here:
* Number of `nulls` = Number of tokens passed(comman seperated)
* Code snippet works fine of local but same exact code have this issue when run in AWS Lambda function. 
    Both cases have same request options,  same endpoint.
* Based on testing the endpoint, I can to the point that endpoint returns `null` when the token(s) is malformed or incorrect. AFAIK the tokens are correct so is there any way I check the logs of what judge0 is recieving in the token params?
Or are there any other reasons why `null` is appearing?

* API response is (when 2 tokens are send) - 
```
{
    "submissions": [
        null,
        null
    ]
}
```
4. Request code snippet - 
```
... extra code
return new Promise(function (resolve, reject) {
    const options = {
      method: 'GET',
      url: `${BASE_URL}/submissions/batch`,
      qs: {
        // hard coded the tokens in the application so as to remove any case of wrong input error.
        tokens: '8ced716a-22ef-426f-8b53-b336b3b16b4a,9b8d77fc-9ace-47d4-b48c-70b212c8b4fe',
        base64_encoded: 'true',
        fields: '*',
      },
      headers: {
        'X-RapidAPI-Key': JUDGE_KEY,
        'X-RapidAPI-Host': JUDGE_HOST,
        useQueryString: true,
      },
      json: true, // return response in json
    };
    request(options, function (error, _response, body) {
      if (error) {
        reject(error);
      }
      resolve(body);
    });
  });
... extra code
```

**Comment by niteshrawat1995** [comment]
Hi @hermanzdosilovic , another interesting thing I notice is that when I use tokens, which are obtained by calling create batch submission api via lambda function, they gives `null` when used over the rapid api dashboard or even from localhost. 

Is there something I am missing here?

**Comment by hermanzdosilovic** [comment]
Hi @niteshrawat1995,

this is the Judge0 Shared Cloud-specific problem.

The problem could be that create and get routes are hitting different Judge0 regions.

Judge0 region is automatically chosen and it depends on the caller's IP address.

You can choose a fixed region by sending a header with the key `X-Judge0-Region` and with one of the following value: `AS`, `EU`, or `NA`.

Hope this helps.

**Comment by niteshrawat1995** [comment]
Ah! That fixed it! 🎉  
Thank you for your help @hermanzdosilovic 😄 
I am just wondering is this piece of information present in any documentation that I missed?
