### ISSUE TITLE
Why callback_url not work?

### ISSUE THREAD

**Issue by alexwenbj** [judge0/judge0#404]
Hi everyone, I am new to Judge0 and I want to use the callback_url when the execution is finished. However, it seems that Judge0 does not invoke the callback_url after execution. I am using the Judge0 v1.13 docker image.My post data looks like this:
```
  $arr = array(
            "language_id" => $language,
            "compiler_options" => $compile_args[$language],
            "redirect_stderr_to_stdout" => true,
            "source_code" => $code,
            "stdin" => $input,
            "callback_url" => $callback_url,
        );
```
Could someone give me a hint for this? Thank you in advance.

**Comment by alexwenbj** [comment]
My fault.Close.

**Comment by agulencina96** [comment]
> My fault.Close.

What is your fault? I'm facing the same issue

**Comment by alexwenbj** [comment]
Sorry, it was a long time ago, so I'm not very sure about the problem. However, it might be most important to ensure that the callback server is accessible, especially when using localhost as the server.
