### ISSUE TITLE
Is there a way to remove past submission after particular period of time

### ISSUE THREAD

**Issue by thisis-vishal** [judge0/judge0#467]
I am trying to remove all the past submissions from postgreSQL stored in docker container.
Is there any configuration to delete all the past submission data.

**Comment by leho-dev** [comment]
Did you find solution? I have created an API that automatically clears submissions at 12AM every month using Appscript. Do you have another solution better?

**Comment by thisis-vishal** [comment]
> Did you find solution? I have created an API that automatically clears submissions at 12AM every month using Appscript. Do you have another solution better?

Actually I did same by exposing the docker port for postgresql and used go routines to clear submission every hour.
