### ISSUE TITLE
Sensitive data is outputted to server logs

### ISSUE THREAD

**Issue by evsasha** [judge0/judge0#478]
Recently updated to 1.13.1 to fix three new CVEs.

And I found that now upon server start, all environment variables, including logins and passwords, are outputted to the server log.

https://github.com/judge0/judge0/blob/master/scripts/server#L7

Is this a bug or a feature?

If it's a bug, it can be avoided like this:

```shell
#!/bin/bash
# Script for running Judge0 server.
#
# Usage: ./scripts/server
#
source ./scripts/load-config
export | sudo tee /api/environment > /dev/null # do not print envs to logs

for i in $(seq 1 $RESTART_MAX_TRIES); do
    [[ -f tmp/pids/server.pid ]] && rm -f tmp/pids/server.pid

    rails db:create db:migrate db:seed
    rails s -b 0.0.0.0
    [[ $? -eq 0 ]] && break
    sleep 2s
done
```

**Comment by evsasha** [comment]
You can also notice that a service user doesn't need login privileges, a home directory, and it's better to set the user ID below 1000, for example, 999, to avoid warnings during image building:

```
useradd warning: judge0's uid 1000 is greater than SYS_UID_MAX 99
```

Here's how user creation might look like:

```dockerfile
RUN useradd -u 999 -m -r -s /usr/sbin/nologin -d /nonexistent judge0 && \
    echo "judge0  ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers && \
    chown judge0: /api/tmp/
```

**Comment by hermanzdosilovic** [comment]
Please use https://github.com/judge0/judge0/security/advisories for security related issues.

Thank you.
