### ISSUE TITLE
Submission is staying in queue only.

### ISSUE THREAD

**Issue by Talha-ai** [judge0/judge0#481]
Hello,
I hosted judge0 locally on my pc and creation of submission is working fine, but when i get the submission, its sayings its in queue. I tried waiting for 5 mins, its still saying its in queue. Why so?

<img width="860" alt="image" src="https://github.com/judge0/judge0/assets/59223186/c7b41659-57fc-4583-a825-cc1efc23762d">

And getting statuses always give me 14 statuses, all with different descriptions. Are these by default? How to check status of a particular submission?

<img width="866" alt="image" src="https://github.com/judge0/judge0/assets/59223186/ae859506-32de-498d-9037-177ce5525d2c">

It got accepted now. Any reason wht its slow?

<img width="860" alt="image" src="https://github.com/judge0/judge0/assets/59223186/edcf3e8b-7418-427b-807b-3166e038f37e">

**Comment by Talha-ai** [comment]
Now its working fine, made some changes in ubuntu config, prbly tht was the issue

**Comment by vxibh** [comment]
what changes did you do? help me out please
