### ISSUE TITLE
No such file or directory @ rb_sysopen. Changed to cgroup in /etc/default/grub in Ubuntu 22.0.

### ISSUE THREAD

**Issue by vr2432** [judge0/judge0#484]
![Screenshot from 2024-06-08 12-44-35](https://github.com/judge0/judge0/assets/125731235/3c3c6a45-5b95-4cc5-96f3-1308e9df2603)
But 
docker info still shows cgroup version v2. I tried #325  also. but issue not resolved.

**Comment by VijayRavichander** [comment]
Did this resolve for you ?

**Comment by vr2432** [comment]
Yes.

**Comment by karansojitra-trootech** [comment]
Can you tell me, How you resolve this please,. 

I've configured same as it is described into the documentation. 
Still not working... 

Please assist me with this.
