### ISSUE TITLE
Self configuring nginx reverse proxy does not work

### ISSUE THREAD

**Issue by Kagenui-yozuru** [judge0/judge0#490]
I want to access my jude0 service through HTTPS, and according to my past habit, I will use nginx for reverse proxy.
```
    server{
        listen 443 ssl;

        server_name judge0.example.com;
        ssl_certificate      "/etc/nginx/conf.d/cert/example.com/cert.pem";
        ssl_certificate_key  "/etc/nginx/conf.d/cert/example.com/key.pem"; 


        location / {
            proxy_pass http://judge0-server:2358;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
```
Afterwards, I accessed it through a browser `https://judge0.example.com` And `https://judge0.example.com/languages/ `They can all work normally
But once I try to use Postman or use HTTP client access in my program `https://judge0.example.com` , it will prompt `Connection reset` or `Error: read ECONNRESET`

This leaves me completely clueless. I noticed that you seem to have used more complex methods to achieve HTTPS access.
I have looked at the name of the image you are using and speculate that you are also using nginx to reverse proxy the jude0 service.
So I want to know if you have any additional configurations, or what **extra** precautions do I need to take when configuring? I have no idea where to solve the problem now.

**Comment by matheusschreiber** [comment]
I dont know if this has anything to do with your problem but there are some things I did differently in my nginx reverse-proxy configuration that worked for me

1. I didnt use quotes on paths here
>  ssl_certificate      "/etc/nginx/conf.d/cert/example.com/cert.pem";
>  ssl_certificate_key  "/etc/nginx/conf.d/cert/example.com/key.pem"; 

2. Also, I used `judge0.example.com` on the path as well, not only `example.com`

3. Here, I used `localhost` instead of `judge0-server`
> proxy_pass http://judge0-server:2358;

4. I added this extra header
> proxy_set_header X-Forwarded-Proto $scheme;

5. At last, I added this redirection configuration (HTTP -> HTTPS)
```
server {
    listen 80;
    server_name judge0.example.com;

    location / {
        return 301 https://$host$request_uri;
    }
}
```

**Comment by Kagenui-yozuru** [comment]
> I dont know if this has anything to do with your problem but there are some things I did differently in my nginx reverse-proxy configuration that worked for me我不知道这是否与你的问题有关，但我在nginx反向代理配置中采用了一些不同的方法，对我很有效
> 
> 1. I didnt use quotes on paths here我没有在这里的路径上使用引号
> 
> > ssl_certificate      "/etc/nginx/conf.d/cert/example.com/cert.pem";ssl_certificate "/etc/nginx/conf.d/cert/example.com/cert.pem"；
> > ssl_certificate_key  "/etc/nginx/conf.d/cert/example.com/key.pem";ssl_certificate_key "/etc/nginx/conf.d/cert/example.com/key.pem"；
> 
> 2. Also, I used `judge0.example.com` on the path as well, not only `example.com`此外，我还在路径上使用了 `judge0.example.com` ，而不仅仅是 `example.com`
> 3. Here, I used `localhost` instead of `judge0-server`在这里，我使用了 `localhost` 而不是 `judge0-server`
> 
> > proxy_pass http://judge0-server:2358;proxy_pass http://judge0-server:2358；
> 
> 4. I added this extra header我添加了这个额外的页眉
> 
> > proxy_set_header X-Forwarded-Proto $scheme;proxy_set_header X-Forwarded-Proto $scheme；
> 
> 5. At last, I added this redirection configuration (HTTP -> HTTPS)最后，我添加了以下重定向配置（HTTP -> HTTPS）
> 
> ```
> server {
>     listen 80;
>     server_name judge0.example.com;
> 
>     location / {
>         return 301 https://$host$request_uri;
>     }
> }
> ```

Thank you very much for your answer.
So far I found the reason for the issue. In my country there is a policy called ICP filing, which requires that the domain name and the server are authenticated before DNS resolution can work properly.
Otherwise, the request from DNS resolution will be interrupted (and when using a non-graphical http client, it will even return an empty response body without telling you why).
Thanks again for your serious answer, I will close this issue.
F* ICP Policy
