### ISSUE TITLE
ERROR: The Compose file './docker-compose.yml' is invalid

### ISSUE THREAD

**Issue by axy1976** [judge0/judge0#501]
When i hit this command `docker-compose up -d db redis`

    root@e2e-96-160:~/judge0-v1.13.1# docker-compose up -d db redis

    ERROR: The Compose file './docker-compose.yml' is invalid because:
    Unsupported config option for volumes: 'data'
    Unsupported config option for x-logging: 'logging'
    Unsupported config option for services: 'server'

might be there is docker(27.2.1) and docker-compose(1.24.1) version mismatch issue installed versions are given, please let me know if they are wrong ?

**Comment by axy1976** [comment]
Problem got resolved i am using docker-compose 1.24.1 instead of 1.27.X or later

**Comment by AnuprabhSingh** [comment]
> Problem got resolved i am using docker-compose 1.24.1 instead of 1.27.X or later

hey I am also facing the same issue, can you please help me how did you resolve this?

**Comment by axy1976** [comment]
> > Problem got resolved i am using docker-compose 1.24.1 instead of 1.27.X or later
> 
> hey I am also facing the same issue, can you please help me how did you resolve this?

check your docker-compose version, it should be 1.24.1

**Comment by UncleDrewGo** [comment]
Hey I resolve this with follow config ,root cause is docker-componse version is not match .you just adjust 这 different version special ，it will work well

`version: '3'
services:
  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    logging:
      driver: json-file
      options:
        max-size: 100M
    restart: always
  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    logging:
      driver: json-file
      options:
        max-size: 100M
    restart: always
  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - ./data/postgresql/data/:/var/lib/postgresql/data/
    logging:
      driver: json-file
      options:
        max-size: 100M
    restart: always
  redis:
    image: redis:7.2.4
    command:
      - "bash"
      - "-c"
      - 'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    env_file: judge0.conf
    logging:
      driver: json-file
      options:
        max-size: 100M
    restart: always
volumes:
  data`
